ERROR 2022-08-19 17:07:02,413 retry_on_timeout 116337 140167959324416 429-{"code":"429000","msg":"Too Many Requests"}
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 18, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/exchange/exchange.py", line 49, in create_market_order
    exchange_order = self._sdk_exchange.trade_client.create_market_order(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/trade/trade.py", line 370, in create_market_order
    return self._request('POST', '/api/v1/orders', params=params)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 91, in _request
    return self.check_response_data(response_data)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 110, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 429-{"code":"429000","msg":"Too Many Requests"}
ERROR 2022-08-19 17:09:02,397 api_exception_handler 116538 139940570593024 'NoneType' object has no attribute 'close_position'
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/views/bot.py", line 61, in post
    FuturesBotTrader.stop_bot('kucoin_main', bot_id)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/trader.py", line 58, in stop_bot
    return bot_handler.stop_bot(credential_id, bot_id)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 494, in stop_bot
    bot.close_position(test=is_test)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/models/bot.py", line 213, in close_position
    self._private_client.close_position(self.position.signal.symbol)
AttributeError: 'NoneType' object has no attribute 'close_position'
ERROR 2022-08-19 17:12:16,737 retry_on_timeout 116921 140462642562816 429-{"code":"429000","msg":"Too Many Requests"}
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 18, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/exchange/exchange.py", line 49, in create_market_order
    exchange_order = self._sdk_exchange.trade_client.create_market_order(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/trade/trade.py", line 370, in create_market_order
    return self._request('POST', '/api/v1/orders', params=params)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 91, in _request
    return self.check_response_data(response_data)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 110, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 429-{"code":"429000","msg":"Too Many Requests"}
ERROR 2022-08-19 17:12:42,748 retry_on_timeout 116921 140462642562816 429-{"code":"429000","msg":"Too Many Requests"}
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 18, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/exchange/exchange.py", line 49, in create_market_order
    exchange_order = self._sdk_exchange.trade_client.create_market_order(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/trade/trade.py", line 370, in create_market_order
    return self._request('POST', '/api/v1/orders', params=params)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 91, in _request
    return self.check_response_data(response_data)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 110, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 429-{"code":"429000","msg":"Too Many Requests"}
ERROR 2022-08-19 17:12:48,791 retry_on_timeout 116921 140462642562816 429-{"code":"429000","msg":"Too Many Requests"}
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 18, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/exchange/exchange.py", line 49, in create_market_order
    exchange_order = self._sdk_exchange.trade_client.create_market_order(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/trade/trade.py", line 370, in create_market_order
    return self._request('POST', '/api/v1/orders', params=params)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 91, in _request
    return self.check_response_data(response_data)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 110, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 429-{"code":"429000","msg":"Too Many Requests"}
ERROR 2022-08-19 17:12:54,633 retry_on_timeout 116921 140462642562816 429-{"code":"429000","msg":"Too Many Requests"}
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 18, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/exchange/exchange.py", line 49, in create_market_order
    exchange_order = self._sdk_exchange.trade_client.create_market_order(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/trade/trade.py", line 370, in create_market_order
    return self._request('POST', '/api/v1/orders', params=params)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 91, in _request
    return self.check_response_data(response_data)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 110, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 429-{"code":"429000","msg":"Too Many Requests"}
ERROR 2022-08-19 17:13:05,194 retry_on_timeout 116921 140462642562816 429-{"code":"429000","msg":"Too Many Requests"}
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 18, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/exchange/exchange.py", line 49, in create_market_order
    exchange_order = self._sdk_exchange.trade_client.create_market_order(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/trade/trade.py", line 370, in create_market_order
    return self._request('POST', '/api/v1/orders', params=params)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 91, in _request
    return self.check_response_data(response_data)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 110, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 429-{"code":"429000","msg":"Too Many Requests"}
ERROR 2022-08-19 17:13:11,204 retry_on_timeout 116921 140462642562816 429-{"code":"429000","msg":"Too Many Requests"}
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 18, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/exchange/exchange.py", line 49, in create_market_order
    exchange_order = self._sdk_exchange.trade_client.create_market_order(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/trade/trade.py", line 370, in create_market_order
    return self._request('POST', '/api/v1/orders', params=params)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 91, in _request
    return self.check_response_data(response_data)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 110, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 429-{"code":"429000","msg":"Too Many Requests"}
ERROR 2022-08-19 17:13:21,670 retry_on_timeout 116921 140462642562816 429-{"code":"429000","msg":"Too Many Requests"}
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 18, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/exchange/exchange.py", line 49, in create_market_order
    exchange_order = self._sdk_exchange.trade_client.create_market_order(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/trade/trade.py", line 370, in create_market_order
    return self._request('POST', '/api/v1/orders', params=params)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 91, in _request
    return self.check_response_data(response_data)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 110, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 429-{"code":"429000","msg":"Too Many Requests"}
ERROR 2022-08-19 17:13:27,678 retry_on_timeout 116921 140462642562816 429-{"code":"429000","msg":"Too Many Requests"}
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 18, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/exchange/exchange.py", line 49, in create_market_order
    exchange_order = self._sdk_exchange.trade_client.create_market_order(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/trade/trade.py", line 370, in create_market_order
    return self._request('POST', '/api/v1/orders', params=params)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 91, in _request
    return self.check_response_data(response_data)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 110, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 429-{"code":"429000","msg":"Too Many Requests"}
ERROR 2022-08-19 17:13:33,526 retry_on_timeout 116921 140462642562816 429-{"code":"429000","msg":"Too Many Requests"}
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 18, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/exchange/exchange.py", line 49, in create_market_order
    exchange_order = self._sdk_exchange.trade_client.create_market_order(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/trade/trade.py", line 370, in create_market_order
    return self._request('POST', '/api/v1/orders', params=params)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 91, in _request
    return self.check_response_data(response_data)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 110, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 429-{"code":"429000","msg":"Too Many Requests"}
ERROR 2022-08-19 17:13:39,447 retry_on_timeout 116921 140462642562816 429-{"code":"429000","msg":"Too Many Requests"}
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 18, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/exchange/exchange.py", line 49, in create_market_order
    exchange_order = self._sdk_exchange.trade_client.create_market_order(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/trade/trade.py", line 370, in create_market_order
    return self._request('POST', '/api/v1/orders', params=params)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 91, in _request
    return self.check_response_data(response_data)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 110, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 429-{"code":"429000","msg":"Too Many Requests"}
ERROR 2022-08-19 17:14:04,475 retry_on_timeout 116921 140462642562816 429-{"code":"429000","msg":"Too Many Requests"}
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 18, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/exchange/exchange.py", line 49, in create_market_order
    exchange_order = self._sdk_exchange.trade_client.create_market_order(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/trade/trade.py", line 370, in create_market_order
    return self._request('POST', '/api/v1/orders', params=params)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 91, in _request
    return self.check_response_data(response_data)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 110, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 429-{"code":"429000","msg":"Too Many Requests"}
ERROR 2022-08-19 17:14:15,181 retry_on_timeout 116921 140462642562816 429-{"code":"429000","msg":"Too Many Requests"}
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 18, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/exchange/exchange.py", line 49, in create_market_order
    exchange_order = self._sdk_exchange.trade_client.create_market_order(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/trade/trade.py", line 370, in create_market_order
    return self._request('POST', '/api/v1/orders', params=params)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 91, in _request
    return self.check_response_data(response_data)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 110, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 429-{"code":"429000","msg":"Too Many Requests"}
ERROR 2022-08-19 17:14:21,064 retry_on_timeout 116921 140462642562816 429-{"code":"429000","msg":"Too Many Requests"}
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 18, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/exchange/exchange.py", line 49, in create_market_order
    exchange_order = self._sdk_exchange.trade_client.create_market_order(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/trade/trade.py", line 370, in create_market_order
    return self._request('POST', '/api/v1/orders', params=params)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 91, in _request
    return self.check_response_data(response_data)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 110, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 429-{"code":"429000","msg":"Too Many Requests"}
ERROR 2022-08-19 17:14:26,877 retry_on_timeout 116921 140462642562816 429-{"code":"429000","msg":"Too Many Requests"}
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 18, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/exchange/exchange.py", line 49, in create_market_order
    exchange_order = self._sdk_exchange.trade_client.create_market_order(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/trade/trade.py", line 370, in create_market_order
    return self._request('POST', '/api/v1/orders', params=params)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 91, in _request
    return self.check_response_data(response_data)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 110, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 429-{"code":"429000","msg":"Too Many Requests"}
ERROR 2022-08-19 17:15:00,512 api_exception_handler 117108 140109332600576 Method "GET" not allowed.
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/rest_framework/views.py", line 167, in http_method_not_allowed
    raise exceptions.MethodNotAllowed(request.method)
rest_framework.exceptions.MethodNotAllowed: Method "GET" not allowed.
ERROR 2022-08-19 17:15:13,735 retry_on_timeout 117108 140109240313600 429-{"code":"429000","msg":"Too Many Requests"}
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 18, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/exchange/exchange.py", line 49, in create_market_order
    exchange_order = self._sdk_exchange.trade_client.create_market_order(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/trade/trade.py", line 370, in create_market_order
    return self._request('POST', '/api/v1/orders', params=params)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 91, in _request
    return self.check_response_data(response_data)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 110, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 429-{"code":"429000","msg":"Too Many Requests"}
ERROR 2022-08-19 17:15:19,729 retry_on_timeout 117108 140109240313600 429-{"code":"429000","msg":"Too Many Requests"}
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 18, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/exchange/exchange.py", line 49, in create_market_order
    exchange_order = self._sdk_exchange.trade_client.create_market_order(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/trade/trade.py", line 370, in create_market_order
    return self._request('POST', '/api/v1/orders', params=params)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 91, in _request
    return self.check_response_data(response_data)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 110, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 429-{"code":"429000","msg":"Too Many Requests"}
ERROR 2022-08-19 17:15:25,595 retry_on_timeout 117108 140109240313600 429-{"code":"429000","msg":"Too Many Requests"}
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 18, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/exchange/exchange.py", line 49, in create_market_order
    exchange_order = self._sdk_exchange.trade_client.create_market_order(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/trade/trade.py", line 370, in create_market_order
    return self._request('POST', '/api/v1/orders', params=params)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 91, in _request
    return self.check_response_data(response_data)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 110, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 429-{"code":"429000","msg":"Too Many Requests"}
ERROR 2022-08-19 17:22:41,518 retry_on_timeout 117790 139686885074688 429-{"code":"429000","msg":"Too Many Requests"}
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 18, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/exchange/exchange.py", line 49, in create_market_order
    exchange_order = self._sdk_exchange.trade_client.create_market_order(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/trade/trade.py", line 370, in create_market_order
    return self._request('POST', '/api/v1/orders', params=params)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 91, in _request
    return self.check_response_data(response_data)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 110, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 429-{"code":"429000","msg":"Too Many Requests"}
ERROR 2022-08-19 17:22:52,596 retry_on_timeout 117790 139686885074688 429-{"code":"429000","msg":"Too Many Requests"}
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 18, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/exchange/exchange.py", line 38, in create_limit_order
    exchange_order = self._sdk_exchange.trade_client.create_limit_order(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/trade/trade.py", line 337, in create_limit_order
    return self._request('POST', '/api/v1/orders', params=params)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 91, in _request
    return self.check_response_data(response_data)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 110, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 429-{"code":"429000","msg":"Too Many Requests"}
ERROR 2022-08-19 17:27:17,934 bot_handler 117790 139686927021824 Creating bot failed because position with symbol CRV/USDT is duplicate!
ERROR 2022-08-19 17:42:13,014 api_exception_handler 119436 140627579340544 'symbol'
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/views/signal.py", line 61, in post
    FuturesBotTrader.create_bot(bot_data)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/trader.py", line 27, in create_bot
    return bot_handler.create_bot(exchange_id=bot_data['exchange_id'],
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 51, in create_bot
    if self.validate_bot_data(exchange_id, credential_id, position_data['signal']['symbol']):
KeyError: 'symbol'
ERROR 2022-08-19 17:44:56,021 retry_on_timeout 119718 140401361856256 429-{"code":"429000","msg":"Too Many Requests"}
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 18, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/exchange/exchange.py", line 38, in create_limit_order
    exchange_order = self._sdk_exchange.trade_client.create_limit_order(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/trade/trade.py", line 337, in create_limit_order
    return self._request('POST', '/api/v1/orders', params=params)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 91, in _request
    return self.check_response_data(response_data)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 110, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 429-{"code":"429000","msg":"Too Many Requests"}
ERROR 2022-08-19 17:58:36,633 retry_on_timeout 120846 140243141789440 200-{"code":"100001","msg":"Quantity parameter invalid."}
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 18, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/exchange/exchange.py", line 49, in create_market_order
    exchange_order = self._sdk_exchange.trade_client.create_market_order(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/trade/trade.py", line 370, in create_market_order
    return self._request('POST', '/api/v1/orders', params=params)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 91, in _request
    return self.check_response_data(response_data)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 108, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 200-{"code":"100001","msg":"Quantity parameter invalid."}
ERROR 2022-08-19 17:58:42,506 retry_on_timeout 120846 140243141789440 200-{"code":"100001","msg":"Quantity parameter invalid."}
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 18, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/exchange/exchange.py", line 49, in create_market_order
    exchange_order = self._sdk_exchange.trade_client.create_market_order(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/trade/trade.py", line 370, in create_market_order
    return self._request('POST', '/api/v1/orders', params=params)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 91, in _request
    return self.check_response_data(response_data)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 108, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 200-{"code":"100001","msg":"Quantity parameter invalid."}
ERROR 2022-08-19 17:58:48,405 retry_on_timeout 120846 140243141789440 200-{"code":"100001","msg":"Quantity parameter invalid."}
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 18, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/exchange/exchange.py", line 49, in create_market_order
    exchange_order = self._sdk_exchange.trade_client.create_market_order(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/trade/trade.py", line 370, in create_market_order
    return self._request('POST', '/api/v1/orders', params=params)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 91, in _request
    return self.check_response_data(response_data)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 108, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 200-{"code":"100001","msg":"Quantity parameter invalid."}
ERROR 2022-08-19 17:58:54,352 retry_on_timeout 120846 140243141789440 200-{"code":"100001","msg":"Quantity parameter invalid."}
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 18, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/exchange/exchange.py", line 49, in create_market_order
    exchange_order = self._sdk_exchange.trade_client.create_market_order(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/trade/trade.py", line 370, in create_market_order
    return self._request('POST', '/api/v1/orders', params=params)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 91, in _request
    return self.check_response_data(response_data)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 108, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 200-{"code":"100001","msg":"Quantity parameter invalid."}
ERROR 2022-08-19 17:59:00,227 retry_on_timeout 120846 140243141789440 200-{"code":"100001","msg":"Quantity parameter invalid."}
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 18, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/exchange/exchange.py", line 49, in create_market_order
    exchange_order = self._sdk_exchange.trade_client.create_market_order(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/trade/trade.py", line 370, in create_market_order
    return self._request('POST', '/api/v1/orders', params=params)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 91, in _request
    return self.check_response_data(response_data)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 108, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 200-{"code":"100001","msg":"Quantity parameter invalid."}
ERROR 2022-08-19 17:59:06,204 retry_on_timeout 120846 140243141789440 429-{"code":"429000","msg":"Too Many Requests"}
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 18, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/exchange/exchange.py", line 49, in create_market_order
    exchange_order = self._sdk_exchange.trade_client.create_market_order(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/trade/trade.py", line 370, in create_market_order
    return self._request('POST', '/api/v1/orders', params=params)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 91, in _request
    return self.check_response_data(response_data)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 110, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 429-{"code":"429000","msg":"Too Many Requests"}
ERROR 2022-08-19 17:59:12,046 retry_on_timeout 120846 140243141789440 200-{"code":"100001","msg":"Quantity parameter invalid."}
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 18, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/exchange/exchange.py", line 49, in create_market_order
    exchange_order = self._sdk_exchange.trade_client.create_market_order(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/trade/trade.py", line 370, in create_market_order
    return self._request('POST', '/api/v1/orders', params=params)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 91, in _request
    return self.check_response_data(response_data)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 108, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 200-{"code":"100001","msg":"Quantity parameter invalid."}
ERROR 2022-08-19 17:59:17,900 retry_on_timeout 120846 140243141789440 200-{"code":"100001","msg":"Quantity parameter invalid."}
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 18, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/exchange/exchange.py", line 49, in create_market_order
    exchange_order = self._sdk_exchange.trade_client.create_market_order(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/trade/trade.py", line 370, in create_market_order
    return self._request('POST', '/api/v1/orders', params=params)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 91, in _request
    return self.check_response_data(response_data)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 108, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 200-{"code":"100001","msg":"Quantity parameter invalid."}
ERROR 2022-08-19 17:59:23,907 retry_on_timeout 120846 140243141789440 200-{"code":"100001","msg":"Quantity parameter invalid."}
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 18, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/exchange/exchange.py", line 49, in create_market_order
    exchange_order = self._sdk_exchange.trade_client.create_market_order(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/trade/trade.py", line 370, in create_market_order
    return self._request('POST', '/api/v1/orders', params=params)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 91, in _request
    return self.check_response_data(response_data)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 108, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 200-{"code":"100001","msg":"Quantity parameter invalid."}
ERROR 2022-08-19 17:59:29,825 retry_on_timeout 120846 140243141789440 200-{"code":"100001","msg":"Quantity parameter invalid."}
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 18, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/exchange/exchange.py", line 49, in create_market_order
    exchange_order = self._sdk_exchange.trade_client.create_market_order(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/trade/trade.py", line 370, in create_market_order
    return self._request('POST', '/api/v1/orders', params=params)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 91, in _request
    return self.check_response_data(response_data)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 108, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 200-{"code":"100001","msg":"Quantity parameter invalid."}
ERROR 2022-08-19 17:59:34,831 bot_handler 120846 140243141789440 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 255, in run_bots_semi_limit_order_based
    bot.execute_operations2(operations)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/models/bot.py", line 192, in execute_operations2
    exchange_order_id = exchange_order['id']
TypeError: 'NoneType' object is not subscriptable
