ERROR 2022-08-19 18:03:46,145 retry_on_timeout 121394 139689762096896 429-{"code":"429000","msg":"Too Many Requests"}
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 18, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/exchange/exchange.py", line 49, in create_market_order
    exchange_order = self._sdk_exchange.trade_client.create_market_order(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/trade/trade.py", line 370, in create_market_order
    return self._request('POST', '/api/v1/orders', params=params)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 91, in _request
    return self.check_response_data(response_data)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 110, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 429-{"code":"429000","msg":"Too Many Requests"}
ERROR 2022-08-19 18:04:11,301 api_exception_handler 121394 139689871152896 name 'signal' is not defined
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/views/bot.py", line 61, in post
    FuturesBotTrader.stop_bot('kucoin_main', bot_id)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/trader.py", line 58, in stop_bot
    return bot_handler.stop_bot(credential_id, bot_id)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 500, in stop_bot
    bot.close_position(test=is_test)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/models/bot.py", line 213, in close_position
    self._private_client.cancel_all_limit_orders(symbol=signal.symbol)
NameError: name 'signal' is not defined
ERROR 2022-08-19 18:06:45,927 retry_on_timeout 121702 140131473053440 429-{"code":"429000","msg":"Too Many Requests"}
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 18, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/exchange/exchange.py", line 49, in create_market_order
    exchange_order = self._sdk_exchange.trade_client.create_market_order(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/trade/trade.py", line 370, in create_market_order
    return self._request('POST', '/api/v1/orders', params=params)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 91, in _request
    return self.check_response_data(response_data)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 110, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 429-{"code":"429000","msg":"Too Many Requests"}
ERROR 2022-08-19 18:06:54,649 retry_on_timeout 121702 140131473053440 429-{"code":"429000","msg":"Too Many Requests"}
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 18, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/exchange/exchange.py", line 49, in create_market_order
    exchange_order = self._sdk_exchange.trade_client.create_market_order(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/trade/trade.py", line 370, in create_market_order
    return self._request('POST', '/api/v1/orders', params=params)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 91, in _request
    return self.check_response_data(response_data)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 110, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 429-{"code":"429000","msg":"Too Many Requests"}
ERROR 2022-08-19 18:07:00,479 retry_on_timeout 121702 140131473053440 429-{"code":"429000","msg":"Too Many Requests"}
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 18, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/exchange/exchange.py", line 49, in create_market_order
    exchange_order = self._sdk_exchange.trade_client.create_market_order(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/trade/trade.py", line 370, in create_market_order
    return self._request('POST', '/api/v1/orders', params=params)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 91, in _request
    return self.check_response_data(response_data)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 110, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 429-{"code":"429000","msg":"Too Many Requests"}
ERROR 2022-08-19 18:07:06,450 retry_on_timeout 121702 140131473053440 429-{"code":"429000","msg":"Too Many Requests"}
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 18, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/exchange/exchange.py", line 49, in create_market_order
    exchange_order = self._sdk_exchange.trade_client.create_market_order(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/trade/trade.py", line 370, in create_market_order
    return self._request('POST', '/api/v1/orders', params=params)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 91, in _request
    return self.check_response_data(response_data)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 110, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 429-{"code":"429000","msg":"Too Many Requests"}
ERROR 2022-08-19 18:07:12,509 retry_on_timeout 121702 140131473053440 429-{"code":"429000","msg":"Too Many Requests"}
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 18, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/exchange/exchange.py", line 49, in create_market_order
    exchange_order = self._sdk_exchange.trade_client.create_market_order(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/trade/trade.py", line 370, in create_market_order
    return self._request('POST', '/api/v1/orders', params=params)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 91, in _request
    return self.check_response_data(response_data)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 110, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 429-{"code":"429000","msg":"Too Many Requests"}
ERROR 2022-08-19 18:07:18,498 retry_on_timeout 121702 140131473053440 429-{"code":"429000","msg":"Too Many Requests"}
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 18, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/exchange/exchange.py", line 49, in create_market_order
    exchange_order = self._sdk_exchange.trade_client.create_market_order(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/trade/trade.py", line 370, in create_market_order
    return self._request('POST', '/api/v1/orders', params=params)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 91, in _request
    return self.check_response_data(response_data)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 110, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 429-{"code":"429000","msg":"Too Many Requests"}
ERROR 2022-08-19 18:07:27,161 retry_on_timeout 121702 140131473053440 429-{"code":"429000","msg":"Too Many Requests"}
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 18, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/exchange/exchange.py", line 38, in create_limit_order
    exchange_order = self._sdk_exchange.trade_client.create_limit_order(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/trade/trade.py", line 337, in create_limit_order
    return self._request('POST', '/api/v1/orders', params=params)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 91, in _request
    return self.check_response_data(response_data)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 110, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 429-{"code":"429000","msg":"Too Many Requests"}
ERROR 2022-08-19 18:07:33,102 retry_on_timeout 121702 140131473053440 429-{"code":"429000","msg":"Too Many Requests"}
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 18, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/exchange/exchange.py", line 38, in create_limit_order
    exchange_order = self._sdk_exchange.trade_client.create_limit_order(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/trade/trade.py", line 337, in create_limit_order
    return self._request('POST', '/api/v1/orders', params=params)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 91, in _request
    return self.check_response_data(response_data)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 110, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 429-{"code":"429000","msg":"Too Many Requests"}
