ERROR 2022-07-30 00:29:37,892 bot_handler 89194 140322719655680 Task <Task pending name='Task-24272' coro=<KucoinFuturesWsClient.unsubscribe() running at /home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/ws_client.py:58> cb=[_run_until_complete_cb() at /usr/lib/python3.8/asyncio/base_events.py:184]> got Future <Future pending cb=[shield.<locals>._outer_done_callback() at /usr/lib/python3.8/asyncio/tasks.py:902]> attached to a different loop
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 195, in run_bots
    self._start_symbols_price_ticker(bot.exchange_id, price_required_symbols)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 305, in _start_symbols_price_ticker
    price_ticker.stop()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 378, in close_ws
    asyncio.run(ws_client.unsubscribe(ticker_topic))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/ws_client.py", line 58, in unsubscribe
    await self._conn.send_message(req_msg)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/websocket/websocket.py", line 110, in send_message
    await self._socket.send(json.dumps(msg))
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 619, in send
    await self.ensure_open()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 928, in ensure_open
    await asyncio.shield(self.close_connection_task)
RuntimeError: Task <Task pending name='Task-24272' coro=<KucoinFuturesWsClient.unsubscribe() running at /home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/ws_client.py:58> cb=[_run_until_complete_cb() at /usr/lib/python3.8/asyncio/base_events.py:184]> got Future <Future pending cb=[shield.<locals>._outer_done_callback() at /usr/lib/python3.8/asyncio/tasks.py:902]> attached to a different loop
ERROR 2022-07-30 00:29:38,916 bot_handler 89194 140322719655680 Task <Task pending name='Task-24283' coro=<KucoinFuturesWsClient.unsubscribe() running at /home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/ws_client.py:58> cb=[_run_until_complete_cb() at /usr/lib/python3.8/asyncio/base_events.py:184]> got Future <Future pending cb=[shield.<locals>._outer_done_callback() at /usr/lib/python3.8/asyncio/tasks.py:902]> attached to a different loop
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 195, in run_bots
    self._start_symbols_price_ticker(bot.exchange_id, price_required_symbols)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 305, in _start_symbols_price_ticker
    price_ticker.stop()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 378, in close_ws
    asyncio.run(ws_client.unsubscribe(ticker_topic))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/ws_client.py", line 58, in unsubscribe
    await self._conn.send_message(req_msg)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/websocket/websocket.py", line 110, in send_message
    await self._socket.send(json.dumps(msg))
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 619, in send
    await self.ensure_open()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 928, in ensure_open
    await asyncio.shield(self.close_connection_task)
RuntimeError: Task <Task pending name='Task-24283' coro=<KucoinFuturesWsClient.unsubscribe() running at /home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/ws_client.py:58> cb=[_run_until_complete_cb() at /usr/lib/python3.8/asyncio/base_events.py:184]> got Future <Future pending cb=[shield.<locals>._outer_done_callback() at /usr/lib/python3.8/asyncio/tasks.py:902]> attached to a different loop
ERROR 2022-07-30 00:29:39,943 bot_handler 89194 140322719655680 Task <Task pending name='Task-24295' coro=<KucoinFuturesWsClient.unsubscribe() running at /home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/ws_client.py:58> cb=[_run_until_complete_cb() at /usr/lib/python3.8/asyncio/base_events.py:184]> got Future <Future pending cb=[shield.<locals>._outer_done_callback() at /usr/lib/python3.8/asyncio/tasks.py:902]> attached to a different loop
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 195, in run_bots
    self._start_symbols_price_ticker(bot.exchange_id, price_required_symbols)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 305, in _start_symbols_price_ticker
    price_ticker.stop()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 378, in close_ws
    asyncio.run(ws_client.unsubscribe(ticker_topic))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/ws_client.py", line 58, in unsubscribe
    await self._conn.send_message(req_msg)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/websocket/websocket.py", line 110, in send_message
    await self._socket.send(json.dumps(msg))
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 619, in send
    await self.ensure_open()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 928, in ensure_open
    await asyncio.shield(self.close_connection_task)
RuntimeError: Task <Task pending name='Task-24295' coro=<KucoinFuturesWsClient.unsubscribe() running at /home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/ws_client.py:58> cb=[_run_until_complete_cb() at /usr/lib/python3.8/asyncio/base_events.py:184]> got Future <Future pending cb=[shield.<locals>._outer_done_callback() at /usr/lib/python3.8/asyncio/tasks.py:902]> attached to a different loop
ERROR 2022-07-30 00:29:40,963 bot_handler 89194 140322719655680 Task <Task pending name='Task-24306' coro=<KucoinFuturesWsClient.unsubscribe() running at /home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/ws_client.py:58> cb=[_run_until_complete_cb() at /usr/lib/python3.8/asyncio/base_events.py:184]> got Future <Future pending cb=[shield.<locals>._outer_done_callback() at /usr/lib/python3.8/asyncio/tasks.py:902]> attached to a different loop
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 195, in run_bots
    self._start_symbols_price_ticker(bot.exchange_id, price_required_symbols)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 305, in _start_symbols_price_ticker
    price_ticker.stop()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 378, in close_ws
    asyncio.run(ws_client.unsubscribe(ticker_topic))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/ws_client.py", line 58, in unsubscribe
    await self._conn.send_message(req_msg)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/websocket/websocket.py", line 110, in send_message
    await self._socket.send(json.dumps(msg))
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 619, in send
    await self.ensure_open()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 928, in ensure_open
    await asyncio.shield(self.close_connection_task)
RuntimeError: Task <Task pending name='Task-24306' coro=<KucoinFuturesWsClient.unsubscribe() running at /home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/ws_client.py:58> cb=[_run_until_complete_cb() at /usr/lib/python3.8/asyncio/base_events.py:184]> got Future <Future pending cb=[shield.<locals>._outer_done_callback() at /usr/lib/python3.8/asyncio/tasks.py:902]> attached to a different loop
ERROR 2022-07-30 00:29:41,982 bot_handler 89194 140322719655680 Task <Task pending name='Task-24318' coro=<KucoinFuturesWsClient.unsubscribe() running at /home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/ws_client.py:58> cb=[_run_until_complete_cb() at /usr/lib/python3.8/asyncio/base_events.py:184]> got Future <Future pending cb=[shield.<locals>._outer_done_callback() at /usr/lib/python3.8/asyncio/tasks.py:902]> attached to a different loop
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 195, in run_bots
    self._start_symbols_price_ticker(bot.exchange_id, price_required_symbols)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 305, in _start_symbols_price_ticker
    price_ticker.stop()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 378, in close_ws
    asyncio.run(ws_client.unsubscribe(ticker_topic))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/ws_client.py", line 58, in unsubscribe
    await self._conn.send_message(req_msg)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/websocket/websocket.py", line 110, in send_message
    await self._socket.send(json.dumps(msg))
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 619, in send
    await self.ensure_open()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 928, in ensure_open
    await asyncio.shield(self.close_connection_task)
RuntimeError: Task <Task pending name='Task-24318' coro=<KucoinFuturesWsClient.unsubscribe() running at /home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/ws_client.py:58> cb=[_run_until_complete_cb() at /usr/lib/python3.8/asyncio/base_events.py:184]> got Future <Future pending cb=[shield.<locals>._outer_done_callback() at /usr/lib/python3.8/asyncio/tasks.py:902]> attached to a different loop
ERROR 2022-07-30 00:29:43,004 bot_handler 89194 140322719655680 Task <Task pending name='Task-24331' coro=<KucoinFuturesWsClient.unsubscribe() running at /home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/ws_client.py:58> cb=[_run_until_complete_cb() at /usr/lib/python3.8/asyncio/base_events.py:184]> got Future <Future pending cb=[shield.<locals>._outer_done_callback() at /usr/lib/python3.8/asyncio/tasks.py:902]> attached to a different loop
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 195, in run_bots
    self._start_symbols_price_ticker(bot.exchange_id, price_required_symbols)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 305, in _start_symbols_price_ticker
    price_ticker.stop()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 378, in close_ws
    asyncio.run(ws_client.unsubscribe(ticker_topic))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/ws_client.py", line 58, in unsubscribe
    await self._conn.send_message(req_msg)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/websocket/websocket.py", line 110, in send_message
    await self._socket.send(json.dumps(msg))
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 619, in send
    await self.ensure_open()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 928, in ensure_open
    await asyncio.shield(self.close_connection_task)
RuntimeError: Task <Task pending name='Task-24331' coro=<KucoinFuturesWsClient.unsubscribe() running at /home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/ws_client.py:58> cb=[_run_until_complete_cb() at /usr/lib/python3.8/asyncio/base_events.py:184]> got Future <Future pending cb=[shield.<locals>._outer_done_callback() at /usr/lib/python3.8/asyncio/tasks.py:902]> attached to a different loop
ERROR 2022-07-30 00:29:44,023 bot_handler 89194 140322719655680 Task <Task pending name='Task-24342' coro=<KucoinFuturesWsClient.unsubscribe() running at /home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/ws_client.py:58> cb=[_run_until_complete_cb() at /usr/lib/python3.8/asyncio/base_events.py:184]> got Future <Future pending cb=[shield.<locals>._outer_done_callback() at /usr/lib/python3.8/asyncio/tasks.py:902]> attached to a different loop
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 195, in run_bots
    self._start_symbols_price_ticker(bot.exchange_id, price_required_symbols)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 305, in _start_symbols_price_ticker
    price_ticker.stop()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 378, in close_ws
    asyncio.run(ws_client.unsubscribe(ticker_topic))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/ws_client.py", line 58, in unsubscribe
    await self._conn.send_message(req_msg)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/websocket/websocket.py", line 110, in send_message
    await self._socket.send(json.dumps(msg))
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 619, in send
    await self.ensure_open()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 928, in ensure_open
    await asyncio.shield(self.close_connection_task)
RuntimeError: Task <Task pending name='Task-24342' coro=<KucoinFuturesWsClient.unsubscribe() running at /home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/ws_client.py:58> cb=[_run_until_complete_cb() at /usr/lib/python3.8/asyncio/base_events.py:184]> got Future <Future pending cb=[shield.<locals>._outer_done_callback() at /usr/lib/python3.8/asyncio/tasks.py:902]> attached to a different loop
ERROR 2022-07-30 00:29:45,042 bot_handler 89194 140322719655680 Task <Task pending name='Task-24354' coro=<KucoinFuturesWsClient.unsubscribe() running at /home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/ws_client.py:58> cb=[_run_until_complete_cb() at /usr/lib/python3.8/asyncio/base_events.py:184]> got Future <Future pending cb=[shield.<locals>._outer_done_callback() at /usr/lib/python3.8/asyncio/tasks.py:902]> attached to a different loop
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 195, in run_bots
    self._start_symbols_price_ticker(bot.exchange_id, price_required_symbols)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 305, in _start_symbols_price_ticker
    price_ticker.stop()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 378, in close_ws
    asyncio.run(ws_client.unsubscribe(ticker_topic))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/ws_client.py", line 58, in unsubscribe
    await self._conn.send_message(req_msg)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/websocket/websocket.py", line 110, in send_message
    await self._socket.send(json.dumps(msg))
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 619, in send
    await self.ensure_open()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 928, in ensure_open
    await asyncio.shield(self.close_connection_task)
RuntimeError: Task <Task pending name='Task-24354' coro=<KucoinFuturesWsClient.unsubscribe() running at /home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/ws_client.py:58> cb=[_run_until_complete_cb() at /usr/lib/python3.8/asyncio/base_events.py:184]> got Future <Future pending cb=[shield.<locals>._outer_done_callback() at /usr/lib/python3.8/asyncio/tasks.py:902]> attached to a different loop
ERROR 2022-07-30 00:29:46,068 bot_handler 89194 140322719655680 Task <Task pending name='Task-24365' coro=<KucoinFuturesWsClient.unsubscribe() running at /home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/ws_client.py:58> cb=[_run_until_complete_cb() at /usr/lib/python3.8/asyncio/base_events.py:184]> got Future <Future pending cb=[shield.<locals>._outer_done_callback() at /usr/lib/python3.8/asyncio/tasks.py:902]> attached to a different loop
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 195, in run_bots
    self._start_symbols_price_ticker(bot.exchange_id, price_required_symbols)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 305, in _start_symbols_price_ticker
    price_ticker.stop()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 378, in close_ws
    asyncio.run(ws_client.unsubscribe(ticker_topic))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/ws_client.py", line 58, in unsubscribe
    await self._conn.send_message(req_msg)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/websocket/websocket.py", line 110, in send_message
    await self._socket.send(json.dumps(msg))
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 619, in send
    await self.ensure_open()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 928, in ensure_open
    await asyncio.shield(self.close_connection_task)
RuntimeError: Task <Task pending name='Task-24365' coro=<KucoinFuturesWsClient.unsubscribe() running at /home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/ws_client.py:58> cb=[_run_until_complete_cb() at /usr/lib/python3.8/asyncio/base_events.py:184]> got Future <Future pending cb=[shield.<locals>._outer_done_callback() at /usr/lib/python3.8/asyncio/tasks.py:902]> attached to a different loop
ERROR 2022-07-30 00:29:47,088 bot_handler 89194 140322719655680 Task <Task pending name='Task-24376' coro=<KucoinFuturesWsClient.unsubscribe() running at /home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/ws_client.py:58> cb=[_run_until_complete_cb() at /usr/lib/python3.8/asyncio/base_events.py:184]> got Future <Future pending cb=[shield.<locals>._outer_done_callback() at /usr/lib/python3.8/asyncio/tasks.py:902]> attached to a different loop
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 195, in run_bots
    self._start_symbols_price_ticker(bot.exchange_id, price_required_symbols)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 305, in _start_symbols_price_ticker
    price_ticker.stop()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 378, in close_ws
    asyncio.run(ws_client.unsubscribe(ticker_topic))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/ws_client.py", line 58, in unsubscribe
    await self._conn.send_message(req_msg)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/websocket/websocket.py", line 110, in send_message
    await self._socket.send(json.dumps(msg))
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 619, in send
    await self.ensure_open()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 928, in ensure_open
    await asyncio.shield(self.close_connection_task)
RuntimeError: Task <Task pending name='Task-24376' coro=<KucoinFuturesWsClient.unsubscribe() running at /home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/ws_client.py:58> cb=[_run_until_complete_cb() at /usr/lib/python3.8/asyncio/base_events.py:184]> got Future <Future pending cb=[shield.<locals>._outer_done_callback() at /usr/lib/python3.8/asyncio/tasks.py:902]> attached to a different loop
ERROR 2022-07-30 00:29:48,108 bot_handler 89194 140322719655680 Task <Task pending name='Task-24388' coro=<KucoinFuturesWsClient.unsubscribe() running at /home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/ws_client.py:58> cb=[_run_until_complete_cb() at /usr/lib/python3.8/asyncio/base_events.py:184]> got Future <Future pending cb=[shield.<locals>._outer_done_callback() at /usr/lib/python3.8/asyncio/tasks.py:902]> attached to a different loop
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 195, in run_bots
    self._start_symbols_price_ticker(bot.exchange_id, price_required_symbols)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 305, in _start_symbols_price_ticker
    price_ticker.stop()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 378, in close_ws
    asyncio.run(ws_client.unsubscribe(ticker_topic))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/ws_client.py", line 58, in unsubscribe
    await self._conn.send_message(req_msg)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/websocket/websocket.py", line 110, in send_message
    await self._socket.send(json.dumps(msg))
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 619, in send
    await self.ensure_open()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 928, in ensure_open
    await asyncio.shield(self.close_connection_task)
RuntimeError: Task <Task pending name='Task-24388' coro=<KucoinFuturesWsClient.unsubscribe() running at /home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/ws_client.py:58> cb=[_run_until_complete_cb() at /usr/lib/python3.8/asyncio/base_events.py:184]> got Future <Future pending cb=[shield.<locals>._outer_done_callback() at /usr/lib/python3.8/asyncio/tasks.py:902]> attached to a different loop
ERROR 2022-07-30 00:29:49,128 bot_handler 89194 140322719655680 Task <Task pending name='Task-24400' coro=<KucoinFuturesWsClient.unsubscribe() running at /home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/ws_client.py:58> cb=[_run_until_complete_cb() at /usr/lib/python3.8/asyncio/base_events.py:184]> got Future <Future pending cb=[shield.<locals>._outer_done_callback() at /usr/lib/python3.8/asyncio/tasks.py:902]> attached to a different loop
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 195, in run_bots
    self._start_symbols_price_ticker(bot.exchange_id, price_required_symbols)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 305, in _start_symbols_price_ticker
    price_ticker.stop()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 378, in close_ws
    asyncio.run(ws_client.unsubscribe(ticker_topic))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/ws_client.py", line 58, in unsubscribe
    await self._conn.send_message(req_msg)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/websocket/websocket.py", line 110, in send_message
    await self._socket.send(json.dumps(msg))
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 619, in send
    await self.ensure_open()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 928, in ensure_open
    await asyncio.shield(self.close_connection_task)
RuntimeError: Task <Task pending name='Task-24400' coro=<KucoinFuturesWsClient.unsubscribe() running at /home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/ws_client.py:58> cb=[_run_until_complete_cb() at /usr/lib/python3.8/asyncio/base_events.py:184]> got Future <Future pending cb=[shield.<locals>._outer_done_callback() at /usr/lib/python3.8/asyncio/tasks.py:902]> attached to a different loop
ERROR 2022-07-30 00:29:50,148 bot_handler 89194 140322719655680 Task <Task pending name='Task-24412' coro=<KucoinFuturesWsClient.unsubscribe() running at /home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/ws_client.py:58> cb=[_run_until_complete_cb() at /usr/lib/python3.8/asyncio/base_events.py:184]> got Future <Future pending cb=[shield.<locals>._outer_done_callback() at /usr/lib/python3.8/asyncio/tasks.py:902]> attached to a different loop
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 195, in run_bots
    self._start_symbols_price_ticker(bot.exchange_id, price_required_symbols)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 305, in _start_symbols_price_ticker
    price_ticker.stop()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 378, in close_ws
    asyncio.run(ws_client.unsubscribe(ticker_topic))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/ws_client.py", line 58, in unsubscribe
    await self._conn.send_message(req_msg)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/websocket/websocket.py", line 110, in send_message
    await self._socket.send(json.dumps(msg))
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 619, in send
    await self.ensure_open()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 928, in ensure_open
    await asyncio.shield(self.close_connection_task)
RuntimeError: Task <Task pending name='Task-24412' coro=<KucoinFuturesWsClient.unsubscribe() running at /home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/ws_client.py:58> cb=[_run_until_complete_cb() at /usr/lib/python3.8/asyncio/base_events.py:184]> got Future <Future pending cb=[shield.<locals>._outer_done_callback() at /usr/lib/python3.8/asyncio/tasks.py:902]> attached to a different loop
ERROR 2022-07-30 00:29:51,179 bot_handler 89194 140322719655680 Task <Task pending name='Task-24425' coro=<KucoinFuturesWsClient.unsubscribe() running at /home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/ws_client.py:58> cb=[_run_until_complete_cb() at /usr/lib/python3.8/asyncio/base_events.py:184]> got Future <Future pending cb=[shield.<locals>._outer_done_callback() at /usr/lib/python3.8/asyncio/tasks.py:902]> attached to a different loop
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 195, in run_bots
    self._start_symbols_price_ticker(bot.exchange_id, price_required_symbols)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 305, in _start_symbols_price_ticker
    price_ticker.stop()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 378, in close_ws
    asyncio.run(ws_client.unsubscribe(ticker_topic))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/ws_client.py", line 58, in unsubscribe
    await self._conn.send_message(req_msg)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/websocket/websocket.py", line 110, in send_message
    await self._socket.send(json.dumps(msg))
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 619, in send
    await self.ensure_open()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 928, in ensure_open
    await asyncio.shield(self.close_connection_task)
RuntimeError: Task <Task pending name='Task-24425' coro=<KucoinFuturesWsClient.unsubscribe() running at /home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/ws_client.py:58> cb=[_run_until_complete_cb() at /usr/lib/python3.8/asyncio/base_events.py:184]> got Future <Future pending cb=[shield.<locals>._outer_done_callback() at /usr/lib/python3.8/asyncio/tasks.py:902]> attached to a different loop
ERROR 2022-07-30 00:29:52,206 bot_handler 89194 140322719655680 Task <Task pending name='Task-24436' coro=<KucoinFuturesWsClient.unsubscribe() running at /home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/ws_client.py:58> cb=[_run_until_complete_cb() at /usr/lib/python3.8/asyncio/base_events.py:184]> got Future <Future pending cb=[shield.<locals>._outer_done_callback() at /usr/lib/python3.8/asyncio/tasks.py:902]> attached to a different loop
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 195, in run_bots
    self._start_symbols_price_ticker(bot.exchange_id, price_required_symbols)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 305, in _start_symbols_price_ticker
    price_ticker.stop()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 378, in close_ws
    asyncio.run(ws_client.unsubscribe(ticker_topic))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/ws_client.py", line 58, in unsubscribe
    await self._conn.send_message(req_msg)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/websocket/websocket.py", line 110, in send_message
    await self._socket.send(json.dumps(msg))
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 619, in send
    await self.ensure_open()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 928, in ensure_open
    await asyncio.shield(self.close_connection_task)
RuntimeError: Task <Task pending name='Task-24436' coro=<KucoinFuturesWsClient.unsubscribe() running at /home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/ws_client.py:58> cb=[_run_until_complete_cb() at /usr/lib/python3.8/asyncio/base_events.py:184]> got Future <Future pending cb=[shield.<locals>._outer_done_callback() at /usr/lib/python3.8/asyncio/tasks.py:902]> attached to a different loop
ERROR 2022-07-30 00:29:53,236 bot_handler 89194 140322719655680 Task <Task pending name='Task-24448' coro=<KucoinFuturesWsClient.unsubscribe() running at /home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/ws_client.py:58> cb=[_run_until_complete_cb() at /usr/lib/python3.8/asyncio/base_events.py:184]> got Future <Future pending cb=[shield.<locals>._outer_done_callback() at /usr/lib/python3.8/asyncio/tasks.py:902]> attached to a different loop
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 195, in run_bots
    self._start_symbols_price_ticker(bot.exchange_id, price_required_symbols)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 305, in _start_symbols_price_ticker
    price_ticker.stop()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 378, in close_ws
    asyncio.run(ws_client.unsubscribe(ticker_topic))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/ws_client.py", line 58, in unsubscribe
    await self._conn.send_message(req_msg)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/websocket/websocket.py", line 110, in send_message
    await self._socket.send(json.dumps(msg))
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 619, in send
    await self.ensure_open()
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 928, in ensure_open
    await asyncio.shield(self.close_connection_task)
RuntimeError: Task <Task pending name='Task-24448' coro=<KucoinFuturesWsClient.unsubscribe() running at /home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/ws_client.py:58> cb=[_run_until_complete_cb() at /usr/lib/python3.8/asyncio/base_events.py:184]> got Future <Future pending cb=[shield.<locals>._outer_done_callback() at /usr/lib/python3.8/asyncio/tasks.py:902]> attached to a different loop
