ERROR 2022-08-07 15:13:07,815 bot_handler 136417 140285956400896 get_operations_limit_based_orders() missing 1 required positional argument: 'self'
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 253, in run_bots_semi_limit_order_based
    operations = strategy_developer.get_operations_limit_based_orders(position=bot.position,
TypeError: get_operations_limit_based_orders() missing 1 required positional argument: 'self'
ERROR 2022-08-07 15:13:08,858 bot_handler 136417 140285956400896 get_operations_limit_based_orders() missing 1 required positional argument: 'self'
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 253, in run_bots_semi_limit_order_based
    operations = strategy_developer.get_operations_limit_based_orders(position=bot.position,
TypeError: get_operations_limit_based_orders() missing 1 required positional argument: 'self'
ERROR 2022-08-07 15:13:09,911 bot_handler 136417 140285956400896 get_operations_limit_based_orders() missing 1 required positional argument: 'self'
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 253, in run_bots_semi_limit_order_based
    operations = strategy_developer.get_operations_limit_based_orders(position=bot.position,
TypeError: get_operations_limit_based_orders() missing 1 required positional argument: 'self'
ERROR 2022-08-07 15:13:10,953 bot_handler 136417 140285956400896 get_operations_limit_based_orders() missing 1 required positional argument: 'self'
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 253, in run_bots_semi_limit_order_based
    operations = strategy_developer.get_operations_limit_based_orders(position=bot.position,
TypeError: get_operations_limit_based_orders() missing 1 required positional argument: 'self'
ERROR 2022-08-07 15:14:32,636 bot_handler 136907 140258728929024 get_operations_limit_based_orders() missing 1 required positional argument: 'self'
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 253, in run_bots_semi_limit_order_based
    operations = strategy_developer.get_operations_limit_based_orders(position=bot.position,
TypeError: get_operations_limit_based_orders() missing 1 required positional argument: 'self'
ERROR 2022-08-07 15:14:33,680 bot_handler 136907 140258728929024 get_operations_limit_based_orders() missing 1 required positional argument: 'self'
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 253, in run_bots_semi_limit_order_based
    operations = strategy_developer.get_operations_limit_based_orders(position=bot.position,
TypeError: get_operations_limit_based_orders() missing 1 required positional argument: 'self'
ERROR 2022-08-07 15:14:34,732 bot_handler 136907 140258728929024 get_operations_limit_based_orders() missing 1 required positional argument: 'self'
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 253, in run_bots_semi_limit_order_based
    operations = strategy_developer.get_operations_limit_based_orders(position=bot.position,
TypeError: get_operations_limit_based_orders() missing 1 required positional argument: 'self'
ERROR 2022-08-07 15:14:35,783 bot_handler 136907 140258728929024 get_operations_limit_based_orders() missing 1 required positional argument: 'self'
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 253, in run_bots_semi_limit_order_based
    operations = strategy_developer.get_operations_limit_based_orders(position=bot.position,
TypeError: get_operations_limit_based_orders() missing 1 required positional argument: 'self'
ERROR 2022-08-07 15:14:36,827 bot_handler 136907 140258728929024 get_operations_limit_based_orders() missing 1 required positional argument: 'self'
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 253, in run_bots_semi_limit_order_based
    operations = strategy_developer.get_operations_limit_based_orders(position=bot.position,
TypeError: get_operations_limit_based_orders() missing 1 required positional argument: 'self'
ERROR 2022-08-07 15:15:21,675 bot_handler 137052 139729563539200 'FuturesTarget' object has no attribute 'trigger_price'
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 253, in run_bots_semi_limit_order_based
    operations = strategy_developer.get_operations_limit_based_orders(position=bot.position,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/strategies/main.py", line 276, in get_operations_limit_based_orders
    price=target2.trigger_price,
AttributeError: 'FuturesTarget' object has no attribute 'trigger_price'
ERROR 2022-08-07 15:15:22,728 bot_handler 137052 139729563539200 'FuturesTarget' object has no attribute 'trigger_price'
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 253, in run_bots_semi_limit_order_based
    operations = strategy_developer.get_operations_limit_based_orders(position=bot.position,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/strategies/main.py", line 276, in get_operations_limit_based_orders
    price=target2.trigger_price,
AttributeError: 'FuturesTarget' object has no attribute 'trigger_price'
ERROR 2022-08-07 15:15:23,781 bot_handler 137052 139729563539200 'FuturesTarget' object has no attribute 'trigger_price'
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 253, in run_bots_semi_limit_order_based
    operations = strategy_developer.get_operations_limit_based_orders(position=bot.position,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/strategies/main.py", line 276, in get_operations_limit_based_orders
    price=target2.trigger_price,
AttributeError: 'FuturesTarget' object has no attribute 'trigger_price'
ERROR 2022-08-07 15:15:24,840 bot_handler 137052 139729563539200 'FuturesTarget' object has no attribute 'trigger_price'
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 253, in run_bots_semi_limit_order_based
    operations = strategy_developer.get_operations_limit_based_orders(position=bot.position,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/strategies/main.py", line 276, in get_operations_limit_based_orders
    price=target2.trigger_price,
AttributeError: 'FuturesTarget' object has no attribute 'trigger_price'
ERROR 2022-08-07 15:15:25,907 bot_handler 137052 139729563539200 'FuturesTarget' object has no attribute 'trigger_price'
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 253, in run_bots_semi_limit_order_based
    operations = strategy_developer.get_operations_limit_based_orders(position=bot.position,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/strategies/main.py", line 276, in get_operations_limit_based_orders
    price=target2.trigger_price,
AttributeError: 'FuturesTarget' object has no attribute 'trigger_price'
ERROR 2022-08-07 15:15:26,963 bot_handler 137052 139729563539200 'FuturesTarget' object has no attribute 'trigger_price'
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 253, in run_bots_semi_limit_order_based
    operations = strategy_developer.get_operations_limit_based_orders(position=bot.position,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/strategies/main.py", line 276, in get_operations_limit_based_orders
    price=target2.trigger_price,
AttributeError: 'FuturesTarget' object has no attribute 'trigger_price'
ERROR 2022-08-07 15:15:28,027 bot_handler 137052 139729563539200 'FuturesTarget' object has no attribute 'trigger_price'
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 253, in run_bots_semi_limit_order_based
    operations = strategy_developer.get_operations_limit_based_orders(position=bot.position,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/strategies/main.py", line 276, in get_operations_limit_based_orders
    price=target2.trigger_price,
AttributeError: 'FuturesTarget' object has no attribute 'trigger_price'
ERROR 2022-08-07 15:18:53,261 retry_on_timeout 137395 140426262603520 429-{"code":"429000","msg":"Too Many Requests"}
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 18, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/exchange/exchange.py", line 49, in create_market_order
    exchange_order = self._sdk_exchange.trade_client.create_market_order(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/trade/trade.py", line 370, in create_market_order
    return self._request('POST', '/api/v1/orders', params=params)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 91, in _request
    return self.check_response_data(response_data)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 110, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 429-{"code":"429000","msg":"Too Many Requests"}
ERROR 2022-08-07 15:19:01,861 retry_on_timeout 137395 140426262603520 429-{"code":"429000","msg":"Too Many Requests"}
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 18, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/exchange/exchange.py", line 38, in create_limit_order
    exchange_order = self._sdk_exchange.trade_client.create_limit_order(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/trade/trade.py", line 337, in create_limit_order
    return self._request('POST', '/api/v1/orders', params=params)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 91, in _request
    return self.check_response_data(response_data)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 110, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 429-{"code":"429000","msg":"Too Many Requests"}
ERROR 2022-08-07 15:19:19,090 retry_on_timeout 137395 140426262603520 200-{"code":"300003","msg":"Balance insufficient. The order would cost 1.9302521433."}
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 18, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/exchange/exchange.py", line 49, in create_market_order
    exchange_order = self._sdk_exchange.trade_client.create_market_order(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/trade/trade.py", line 370, in create_market_order
    return self._request('POST', '/api/v1/orders', params=params)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 91, in _request
    return self.check_response_data(response_data)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 108, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 200-{"code":"300003","msg":"Balance insufficient. The order would cost 1.9302521433."}
ERROR 2022-08-07 15:19:25,011 retry_on_timeout 137395 140426262603520 200-{"code":"300003","msg":"Balance insufficient. The order would cost 1.9298839620."}
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 18, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/exchange/exchange.py", line 49, in create_market_order
    exchange_order = self._sdk_exchange.trade_client.create_market_order(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/trade/trade.py", line 370, in create_market_order
    return self._request('POST', '/api/v1/orders', params=params)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 91, in _request
    return self.check_response_data(response_data)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 108, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 200-{"code":"300003","msg":"Balance insufficient. The order would cost 1.9298839620."}
ERROR 2022-08-07 15:31:56,102 bot_handler 138954 140261335840512 name 'stoploss' is not defined
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 255, in run_bots_semi_limit_order_based
    bot.execute_operations2(operations)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/models/bot.py", line 179, in execute_operations2
    stop_price=stoploss.trigger_price,
NameError: name 'stoploss' is not defined
