ERROR 2022-08-08 11:26:27,833 retry_on_timeout 178996 140156360124224 404-{"code":"404","msg":"Not Found","retry":false,"success":false}
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 18, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/exchange/exchange.py", line 103, in fetch_ticker
    return float(self._sdk_exchange.market_client.get_ticker(symbol)['price'])
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/marke_data/market_data.py", line 418, in get_ticker
    return self._request('GET', '/api/v1/ticker', auth=False, params=params)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 91, in _request
    return self.check_response_data(response_data)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 110, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 404-{"code":"404","msg":"Not Found","retry":false,"success":false}
ERROR 2022-08-08 11:26:33,864 retry_on_timeout 178996 140156360124224 404-{"code":"404","msg":"Not Found","retry":false,"success":false}
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 18, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/exchange/exchange.py", line 103, in fetch_ticker
    return float(self._sdk_exchange.market_client.get_ticker(symbol)['price'])
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/marke_data/market_data.py", line 418, in get_ticker
    return self._request('GET', '/api/v1/ticker', auth=False, params=params)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 91, in _request
    return self.check_response_data(response_data)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 110, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 404-{"code":"404","msg":"Not Found","retry":false,"success":false}
ERROR 2022-08-08 11:26:46,575 bot_handler 178996 140155721594624 create_market_order() missing 1 required positional argument: 'precision'
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/bot_handler.py", line 255, in run_bots_semi_limit_order_based
    bot.execute_operations2(operations)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/models/bot.py", line 168, in execute_operations2
    exchange_order = self._private_client.create_market_order(
TypeError: create_market_order() missing 1 required positional argument: 'precision'
ERROR 2022-08-08 11:32:15,558 retry_on_timeout 179649 140046801704704 404-{"code":"404","msg":"Not Found","retry":false,"success":false}
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 18, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/exchange/exchange.py", line 27, in get_order
    return self._sdk_exchange.trade_client.get_order_details(orderId=order_id)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/trade/trade.py", line 613, in get_order_details
    return self._request('GET', f'/api/v1/orders/{orderId}')
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 91, in _request
    return self.check_response_data(response_data)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 110, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 404-{"code":"404","msg":"Not Found","retry":false,"success":false}
ERROR 2022-08-08 11:32:21,971 retry_on_timeout 179649 140046801704704 404-{"code":"404","msg":"Not Found","retry":false,"success":false}
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 18, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/exchange/exchange.py", line 27, in get_order
    return self._sdk_exchange.trade_client.get_order_details(orderId=order_id)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/trade/trade.py", line 613, in get_order_details
    return self._request('GET', f'/api/v1/orders/{orderId}')
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 91, in _request
    return self.check_response_data(response_data)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 110, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 404-{"code":"404","msg":"Not Found","retry":false,"success":false}
ERROR 2022-08-08 11:32:27,667 retry_on_timeout 179649 140046801704704 404-{"code":"404","msg":"Not Found","retry":false,"success":false}
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 18, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/exchange/exchange.py", line 27, in get_order
    return self._sdk_exchange.trade_client.get_order_details(orderId=order_id)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/trade/trade.py", line 613, in get_order_details
    return self._request('GET', f'/api/v1/orders/{orderId}')
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 91, in _request
    return self.check_response_data(response_data)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 110, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 404-{"code":"404","msg":"Not Found","retry":false,"success":false}
ERROR 2022-08-08 11:32:33,475 retry_on_timeout 179649 140046801704704 404-{"code":"404","msg":"Not Found","retry":false,"success":false}
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 18, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/exchange/exchange.py", line 27, in get_order
    return self._sdk_exchange.trade_client.get_order_details(orderId=order_id)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/trade/trade.py", line 613, in get_order_details
    return self._request('GET', f'/api/v1/orders/{orderId}')
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 91, in _request
    return self.check_response_data(response_data)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 110, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 404-{"code":"404","msg":"Not Found","retry":false,"success":false}
ERROR 2022-08-08 11:32:41,268 retry_on_timeout 179649 140046801704704 404-{"code":"404","msg":"Not Found","retry":false,"success":false}
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 18, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/exchange/exchange.py", line 27, in get_order
    return self._sdk_exchange.trade_client.get_order_details(orderId=order_id)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/trade/trade.py", line 613, in get_order_details
    return self._request('GET', f'/api/v1/orders/{orderId}')
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 91, in _request
    return self.check_response_data(response_data)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 110, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 404-{"code":"404","msg":"Not Found","retry":false,"success":false}
ERROR 2022-08-08 11:32:46,977 retry_on_timeout 179649 140046801704704 404-{"code":"404","msg":"Not Found","retry":false,"success":false}
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 18, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/exchange/exchange.py", line 27, in get_order
    return self._sdk_exchange.trade_client.get_order_details(orderId=order_id)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/trade/trade.py", line 613, in get_order_details
    return self._request('GET', f'/api/v1/orders/{orderId}')
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 91, in _request
    return self.check_response_data(response_data)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 110, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 404-{"code":"404","msg":"Not Found","retry":false,"success":false}
ERROR 2022-08-08 11:32:52,636 retry_on_timeout 179649 140046801704704 404-{"code":"404","msg":"Not Found","retry":false,"success":false}
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 18, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/exchange/exchange.py", line 27, in get_order
    return self._sdk_exchange.trade_client.get_order_details(orderId=order_id)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/trade/trade.py", line 613, in get_order_details
    return self._request('GET', f'/api/v1/orders/{orderId}')
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 91, in _request
    return self.check_response_data(response_data)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 110, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 404-{"code":"404","msg":"Not Found","retry":false,"success":false}
ERROR 2022-08-08 11:32:59,788 retry_on_timeout 179649 140046801704704 404-{"code":"404","msg":"Not Found","retry":false,"success":false}
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 18, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/exchange/exchange.py", line 38, in create_limit_order
    exchange_order = self._sdk_exchange.trade_client.create_limit_order(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/trade/trade.py", line 337, in create_limit_order
    return self._request('POST', '/api/v1/orders', params=params)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 91, in _request
    return self.check_response_data(response_data)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 110, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 404-{"code":"404","msg":"Not Found","retry":false,"success":false}
