ERROR 2022-03-30 23:09:44,591 catch_all_exceptions 14439 139836350527232 func=<function start_signal_generating_by_cci at 0x7f2e58c968b0> args=() kwargs={} message=start_signal_generating_by_cci() missing 4 required positional arguments: 'pb', 'symbol', 'timeframe', and 'n' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
TypeError: start_signal_generating_by_cci() missing 4 required positional arguments: 'pb', 'symbol', 'timeframe', and 'n'

ERROR 2022-03-30 23:10:46,102 catch_all_exceptions 14592 139912435308288 func=<function start_signal_generating_by_cci at 0x7f3fe7826670> args=() kwargs={} message=start_signal_generating_by_cci() missing 4 required positional arguments: 'pb', 'symbol', 'timeframe', and 'n' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
TypeError: start_signal_generating_by_cci() missing 4 required positional arguments: 'pb', 'symbol', 'timeframe', and 'n'

ERROR 2022-03-30 23:11:37,116 catch_all_exceptions 14651 140406966445824 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'BCH/USDT', '1h', 40) kwargs={} message='BCH/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'BCH/USDT'

ERROR 2022-03-30 23:11:37,116 catch_all_exceptions 14651 140407204153088 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'BTC/USDT', '1h', 40) kwargs={} message='BTC/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'BTC/USDT'

ERROR 2022-03-30 23:11:37,117 catch_all_exceptions 14651 140406974838528 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'ETH/USDT', '1h', 40) kwargs={} message='ETH/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'ETH/USDT'

ERROR 2022-03-30 23:11:37,119 catch_all_exceptions 14651 140406958053120 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'BSV/USDT', '1h', 40) kwargs={} message='BSV/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'BSV/USDT'

ERROR 2022-03-30 23:11:37,121 catch_all_exceptions 14651 140407204153088 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'YFI/USDT', '1h', 40) kwargs={} message='YFI/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'YFI/USDT'

ERROR 2022-03-30 23:11:37,121 catch_all_exceptions 14651 140406974838528 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'EOS/USDT', '1h', 40) kwargs={} message='EOS/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'EOS/USDT'

ERROR 2022-03-30 23:11:37,122 catch_all_exceptions 14651 140406958053120 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'DOT/USDT', '1h', 40) kwargs={} message='DOT/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'DOT/USDT'

ERROR 2022-03-30 23:11:37,122 catch_all_exceptions 14651 140406941267712 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'FIL/USDT', '1h', 40) kwargs={} message='FIL/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'FIL/USDT'

ERROR 2022-03-30 23:11:37,123 catch_all_exceptions 14651 140406958053120 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'LTC/USDT', '1h', 40) kwargs={} message='LTC/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'LTC/USDT'

ERROR 2022-03-30 23:11:37,123 catch_all_exceptions 14651 140407204153088 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'XRP/USDT', '1h', 40) kwargs={} message='XRP/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'XRP/USDT'

ERROR 2022-03-30 23:11:37,123 catch_all_exceptions 14651 140406974838528 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'ADA/USDT', '1h', 40) kwargs={} message='ADA/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'ADA/USDT'

ERROR 2022-03-30 23:11:37,123 catch_all_exceptions 14651 140406932875008 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'TRX/USDT', '1h', 40) kwargs={} message='TRX/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'TRX/USDT'

ERROR 2022-03-30 23:11:37,123 catch_all_exceptions 14651 140406941267712 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'GRT/USDT', '1h', 40) kwargs={} message='GRT/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'GRT/USDT'

ERROR 2022-03-30 23:11:37,124 catch_all_exceptions 14651 140406958053120 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'SUSHI/USDT', '1h', 40) kwargs={} message='SUSHI/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'SUSHI/USDT'

ERROR 2022-03-30 23:11:37,124 catch_all_exceptions 14651 140407204153088 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'XLM/USDT', '1h', 40) kwargs={} message='XLM/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'XLM/USDT'

ERROR 2022-03-30 23:11:37,124 catch_all_exceptions 14651 140406974838528 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, '1INCH/USDT', '1h', 40) kwargs={} message='1INCH/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: '1INCH/USDT'

ERROR 2022-03-30 23:11:37,125 catch_all_exceptions 14651 140406924482304 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'ZEC/USDT', '1h', 40) kwargs={} message='ZEC/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'ZEC/USDT'

ERROR 2022-03-30 23:11:37,125 catch_all_exceptions 14651 140406932875008 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'DASH/USDT', '1h', 40) kwargs={} message='DASH/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'DASH/USDT'

ERROR 2022-03-30 23:11:37,125 catch_all_exceptions 14651 140406941267712 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'AAVE/USDT', '1h', 40) kwargs={} message='AAVE/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'AAVE/USDT'

ERROR 2022-03-30 23:11:37,126 catch_all_exceptions 14651 140406958053120 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'KSM/USDT', '1h', 40) kwargs={} message='KSM/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'KSM/USDT'

ERROR 2022-03-30 23:11:37,126 catch_all_exceptions 14651 140406440326912 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'DOGE/USDT', '1h', 40) kwargs={} message='DOGE/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'DOGE/USDT'

ERROR 2022-03-30 23:11:37,127 catch_all_exceptions 14651 140407204153088 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'LUNA/USDT', '1h', 40) kwargs={} message='LUNA/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'LUNA/USDT'

ERROR 2022-03-30 23:11:37,127 catch_all_exceptions 14651 140406974838528 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'VET/USDT', '1h', 40) kwargs={} message='VET/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'VET/USDT'

ERROR 2022-03-30 23:11:37,127 catch_all_exceptions 14651 140406924482304 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'BNB/USDT', '1h', 40) kwargs={} message='BNB/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'BNB/USDT'

ERROR 2022-03-30 23:11:37,128 catch_all_exceptions 14651 140406431934208 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'SXP/USDT', '1h', 40) kwargs={} message='SXP/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'SXP/USDT'

ERROR 2022-03-30 23:11:37,128 catch_all_exceptions 14651 140406932875008 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'SOL/USDT', '1h', 40) kwargs={} message='SOL/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'SOL/USDT'

ERROR 2022-03-30 23:11:37,128 catch_all_exceptions 14651 140406941267712 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'IOST/USDT', '1h', 40) kwargs={} message='IOST/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'IOST/USDT'

ERROR 2022-03-30 23:11:37,129 catch_all_exceptions 14651 140406440326912 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'CRV/USDT', '1h', 40) kwargs={} message='CRV/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'CRV/USDT'

ERROR 2022-03-30 23:11:37,129 catch_all_exceptions 14651 140406958053120 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'ALGO/USDT', '1h', 40) kwargs={} message='ALGO/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'ALGO/USDT'

ERROR 2022-03-30 23:11:37,129 catch_all_exceptions 14651 140407204153088 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'AVAX/USDT', '1h', 40) kwargs={} message='AVAX/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'AVAX/USDT'

ERROR 2022-03-30 23:11:37,129 catch_all_exceptions 14651 140406423541504 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'FTM/USDT', '1h', 40) kwargs={} message='FTM/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'FTM/USDT'

ERROR 2022-03-30 23:11:37,129 catch_all_exceptions 14651 140406974838528 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'MATIC/USDT', '1h', 40) kwargs={} message='MATIC/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'MATIC/USDT'

ERROR 2022-03-30 23:11:37,130 catch_all_exceptions 14651 140406415148800 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'THETA/USDT', '1h', 40) kwargs={} message='THETA/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'THETA/USDT'

ERROR 2022-03-30 23:11:37,130 catch_all_exceptions 14651 140406431934208 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'ATOM/USDT', '1h', 40) kwargs={} message='ATOM/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'ATOM/USDT'

ERROR 2022-03-30 23:11:37,130 catch_all_exceptions 14651 140406924482304 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'CHZ/USDT', '1h', 40) kwargs={} message='CHZ/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'CHZ/USDT'

ERROR 2022-03-30 23:11:37,130 catch_all_exceptions 14651 140406932875008 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'ENJ/USDT', '1h', 40) kwargs={} message='ENJ/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'ENJ/USDT'

ERROR 2022-03-30 23:11:37,131 catch_all_exceptions 14651 140406406756096 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'MANA/USDT', '1h', 40) kwargs={} message='MANA/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'MANA/USDT'

ERROR 2022-03-30 23:11:37,131 catch_all_exceptions 14651 140406941267712 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'DENT/USDT', '1h', 40) kwargs={} message='DENT/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'DENT/USDT'

ERROR 2022-03-30 23:11:37,131 catch_all_exceptions 14651 140406440326912 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'OCEAN/USDT', '1h', 40) kwargs={} message='OCEAN/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'OCEAN/USDT'

ERROR 2022-03-30 23:11:37,132 catch_all_exceptions 14651 140406398363392 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'BAT/USDT', '1h', 40) kwargs={} message='BAT/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'BAT/USDT'

ERROR 2022-03-30 23:11:37,132 catch_all_exceptions 14651 140406958053120 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'XEM/USDT', '1h', 40) kwargs={} message='XEM/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'XEM/USDT'

ERROR 2022-03-30 23:11:37,133 catch_all_exceptions 14651 140407204153088 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'QTUM/USDT', '1h', 40) kwargs={} message='QTUM/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'QTUM/USDT'

ERROR 2022-03-30 23:11:37,133 catch_all_exceptions 14651 140406423541504 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'XTZ/USDT', '1h', 40) kwargs={} message='XTZ/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'XTZ/USDT'

ERROR 2022-03-30 23:11:37,133 catch_all_exceptions 14651 140406389970688 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'SNX/USDT', '1h', 40) kwargs={} message='SNX/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'SNX/USDT'

ERROR 2022-03-30 23:11:37,134 catch_all_exceptions 14651 140406974838528 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'NEO/USDT', '1h', 40) kwargs={} message='NEO/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'NEO/USDT'

ERROR 2022-03-30 23:11:37,134 catch_all_exceptions 14651 140406415148800 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'ONT/USDT', '1h', 40) kwargs={} message='ONT/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'ONT/USDT'

ERROR 2022-03-30 23:11:37,134 catch_all_exceptions 14651 140405903456000 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'XMR/USDT', '1h', 40) kwargs={} message='XMR/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'XMR/USDT'

ERROR 2022-03-30 23:11:37,135 catch_all_exceptions 14651 140406431934208 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'COMP/USDT', '1h', 40) kwargs={} message='COMP/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'COMP/USDT'

ERROR 2022-03-30 23:11:37,135 catch_all_exceptions 14651 140406924482304 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'ETC/USDT', '1h', 40) kwargs={} message='ETC/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'ETC/USDT'

ERROR 2022-03-30 23:11:37,135 catch_all_exceptions 14651 140405895063296 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'WAVES/USDT', '1h', 40) kwargs={} message='WAVES/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'WAVES/USDT'

ERROR 2022-03-30 23:11:37,135 catch_all_exceptions 14651 140406932875008 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'BAND/USDT', '1h', 40) kwargs={} message='BAND/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'BAND/USDT'

ERROR 2022-03-30 23:11:37,136 catch_all_exceptions 14651 140405886670592 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'MKR/USDT', '1h', 40) kwargs={} message='MKR/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'MKR/USDT'

ERROR 2022-03-30 23:11:37,136 catch_all_exceptions 14651 140406406756096 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'RVN/USDT', '1h', 40) kwargs={} message='RVN/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'RVN/USDT'

ERROR 2022-03-30 23:11:37,136 catch_all_exceptions 14651 140405878277888 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'DGB/USDT', '1h', 40) kwargs={} message='DGB/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'DGB/USDT'

ERROR 2022-03-30 23:11:37,137 catch_all_exceptions 14651 140406941267712 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'MIR/USDT', '1h', 40) kwargs={} message='MIR/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'MIR/USDT'

ERROR 2022-03-30 23:11:37,137 catch_all_exceptions 14651 140405869885184 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'SHIB/USDT', '1h', 40) kwargs={} message='SHIB/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'SHIB/USDT'

ERROR 2022-03-30 23:11:37,137 catch_all_exceptions 14651 140406440326912 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'ICP/USDT', '1h', 40) kwargs={} message='ICP/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'ICP/USDT'

ERROR 2022-03-30 23:11:37,137 catch_all_exceptions 14651 140406398363392 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'DYDX/USDT', '1h', 40) kwargs={} message='DYDX/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'DYDX/USDT'

ERROR 2022-03-30 23:11:37,138 catch_all_exceptions 14651 140406958053120 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'AXS/USDT', '1h', 40) kwargs={} message='AXS/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'AXS/USDT'

ERROR 2022-03-30 23:11:37,138 catch_all_exceptions 14651 140405861492480 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'HBAR/USDT', '1h', 40) kwargs={} message='HBAR/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'HBAR/USDT'

ERROR 2022-03-30 23:11:37,138 catch_all_exceptions 14651 140406423541504 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'EGLD/USDT', '1h', 40) kwargs={} message='EGLD/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'EGLD/USDT'

ERROR 2022-03-30 23:11:37,138 catch_all_exceptions 14651 140407204153088 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'ALICE/USDT', '1h', 40) kwargs={} message='ALICE/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'ALICE/USDT'

ERROR 2022-03-30 23:11:37,139 catch_all_exceptions 14651 140405853099776 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'NEAR/USDT', '1h', 40) kwargs={} message='NEAR/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'NEAR/USDT'

ERROR 2022-03-30 23:11:37,139 catch_all_exceptions 14651 140406389970688 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'YGG/USDT', '1h', 40) kwargs={} message='YGG/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'YGG/USDT'

ERROR 2022-03-30 23:11:37,139 catch_all_exceptions 14651 140405366585088 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'SAND/USDT', '1h', 40) kwargs={} message='SAND/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'SAND/USDT'

ERROR 2022-03-30 23:11:37,140 catch_all_exceptions 14651 140406415148800 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'C98/USDT', '1h', 40) kwargs={} message='C98/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'C98/USDT'

ERROR 2022-03-30 23:11:37,140 catch_all_exceptions 14651 140406974838528 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'ONE/USDT', '1h', 40) kwargs={} message='ONE/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'ONE/USDT'

ERROR 2022-03-30 23:11:37,140 catch_all_exceptions 14651 140405903456000 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'VRA/USDT', '1h', 40) kwargs={} message='VRA/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'VRA/USDT'

ERROR 2022-03-30 23:11:37,140 catch_all_exceptions 14651 140405358192384 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'GALA/USDT', '1h', 40) kwargs={} message='GALA/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'GALA/USDT'

ERROR 2022-03-30 23:11:37,142 catch_all_exceptions 14651 140405349799680 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'CHR/USDT', '1h', 40) kwargs={} message='CHR/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'CHR/USDT'

ERROR 2022-03-30 23:11:37,142 catch_all_exceptions 14651 140406431934208 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'TLM/USDT', '1h', 40) kwargs={} message='TLM/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'TLM/USDT'

ERROR 2022-03-30 23:11:37,142 catch_all_exceptions 14651 140406924482304 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'LRC/USDT', '1h', 40) kwargs={} message='LRC/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'LRC/USDT'

ERROR 2022-03-30 23:11:37,143 catch_all_exceptions 14651 140405341406976 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'FLOW/USDT', '1h', 40) kwargs={} message='FLOW/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'FLOW/USDT'

ERROR 2022-03-30 23:11:37,143 catch_all_exceptions 14651 140405895063296 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'IOTX/USDT', '1h', 40) kwargs={} message='IOTX/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'IOTX/USDT'

ERROR 2022-03-30 23:11:37,143 catch_all_exceptions 14651 140406932875008 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'RNDR/USDT', '1h', 40) kwargs={} message='RNDR/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'RNDR/USDT'

ERROR 2022-03-30 23:11:37,143 catch_all_exceptions 14651 140405886670592 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'CRO/USDT', '1h', 40) kwargs={} message='CRO/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'CRO/USDT'

ERROR 2022-03-30 23:11:37,144 catch_all_exceptions 14651 140406406756096 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'WAXP/USDT', '1h', 40) kwargs={} message='WAXP/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'WAXP/USDT'

ERROR 2022-03-30 23:11:37,144 catch_all_exceptions 14651 140405333014272 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'PEOPLE/USDT', '1h', 40) kwargs={} message='PEOPLE/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'PEOPLE/USDT'

ERROR 2022-03-30 23:11:37,144 catch_all_exceptions 14651 140405878277888 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'OMG/USDT', '1h', 40) kwargs={} message='OMG/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'OMG/USDT'

ERROR 2022-03-30 23:11:37,144 catch_all_exceptions 14651 140405324621568 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'LINA/USDT', '1h', 40) kwargs={} message='LINA/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'LINA/USDT'

ERROR 2022-03-30 23:11:37,145 catch_all_exceptions 14651 140406941267712 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'IMX/USDT', '1h', 40) kwargs={} message='IMX/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'IMX/USDT'

ERROR 2022-03-30 23:11:37,145 catch_all_exceptions 14651 140405316228864 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'NFT/USDT', '1h', 40) kwargs={} message='NFT/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'NFT/USDT'

ERROR 2022-03-30 23:11:37,145 catch_all_exceptions 14651 140405869885184 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'CELR/USDT', '1h', 40) kwargs={} message='CELR/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'CELR/USDT'

ERROR 2022-03-30 23:11:37,146 catch_all_exceptions 14651 140404829714176 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'ENS/USDT', '1h', 40) kwargs={} message='ENS/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'ENS/USDT'

ERROR 2022-03-30 23:11:37,146 catch_all_exceptions 14651 140406440326912 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'CELO/USDT', '1h', 40) kwargs={} message='CELO/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'CELO/USDT'

ERROR 2022-03-30 23:11:37,146 catch_all_exceptions 14651 140406398363392 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'CTSI/USDT', '1h', 40) kwargs={} message='CTSI/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'CTSI/USDT'

ERROR 2022-03-30 23:11:37,146 catch_all_exceptions 14651 140406958053120 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'SLP/USDT', '1h', 40) kwargs={} message='SLP/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'SLP/USDT'

ERROR 2022-03-30 23:11:37,147 catch_all_exceptions 14651 140404821321472 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'ARPA/USDT', '1h', 40) kwargs={} message='ARPA/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'ARPA/USDT'

ERROR 2022-03-30 23:11:37,147 catch_all_exceptions 14651 140405861492480 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'KNC/USDT', '1h', 40) kwargs={} message='KNC/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'KNC/USDT'

ERROR 2022-03-30 23:11:37,147 catch_all_exceptions 14651 140404812928768 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'SOS/USDT', '1h', 40) kwargs={} message='SOS/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'SOS/USDT'

ERROR 2022-03-30 23:11:37,147 catch_all_exceptions 14651 140407204153088 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'API3/USDT', '1h', 40) kwargs={} message='API3/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'API3/USDT'

ERROR 2022-03-30 23:11:37,148 catch_all_exceptions 14651 140405853099776 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'AGLD/USDT', '1h', 40) kwargs={} message='AGLD/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'AGLD/USDT'

ERROR 2022-03-30 23:11:37,148 catch_all_exceptions 14651 140406389970688 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'APE/USDT', '1h', 40) kwargs={} message='APE/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'APE/USDT'

ERROR 2022-03-30 23:11:37,148 catch_all_exceptions 14651 140405366585088 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'SRM/USDT', '1h', 40) kwargs={} message='SRM/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'SRM/USDT'

ERROR 2022-03-30 23:11:37,149 catch_all_exceptions 14651 140404804536064 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'JASMY/USDT', '1h', 40) kwargs={} message='JASMY/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'JASMY/USDT'

ERROR 2022-03-30 23:11:37,149 catch_all_exceptions 14651 140406415148800 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'ZIL/USDT', '1h', 40) kwargs={} message='ZIL/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 72, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'ZIL/USDT'

ERROR 2022-03-30 23:11:40,138 catch_all_exceptions 14651 140406423541504 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'ROSE/USDT', '1h', 40) kwargs={} message=name 'cc' is not defined traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 77, in start_signal_generating_by_cci
    print(cc, prev_cci)
NameError: name 'cc' is not defined

ERROR 2022-03-30 23:11:40,558 catch_all_exceptions 14651 140406949660416 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'UNI/USDT', '1h', 40) kwargs={} message=name 'cc' is not defined traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 77, in start_signal_generating_by_cci
    print(cc, prev_cci)
NameError: name 'cc' is not defined

ERROR 2022-03-30 23:11:41,570 catch_all_exceptions 14651 140406966445824 func=<function start_signal_generating_by_cci at 0x7fb319877670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7fb319878940>, 'LINK/USDT', '1h', 40) kwargs={} message=name 'cc' is not defined traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 77, in start_signal_generating_by_cci
    print(cc, prev_cci)
NameError: name 'cc' is not defined

ERROR 2022-03-30 23:12:40,645 catch_all_exceptions 14828 139710487594752 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'BTC/USDT', '1h', 40) kwargs={} message='BTC/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'BTC/USDT'

ERROR 2022-03-30 23:12:40,648 catch_all_exceptions 14828 139710487594752 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'BSV/USDT', '1h', 40) kwargs={} message='BSV/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'BSV/USDT'

ERROR 2022-03-30 23:12:40,648 catch_all_exceptions 14828 139710252971776 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'ETH/USDT', '1h', 40) kwargs={} message='ETH/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'ETH/USDT'

ERROR 2022-03-30 23:12:40,656 catch_all_exceptions 14828 139710244579072 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'BCH/USDT', '1h', 40) kwargs={} message='BCH/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'BCH/USDT'

ERROR 2022-03-30 23:12:40,659 catch_all_exceptions 14828 139710487594752 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'YFI/USDT', '1h', 40) kwargs={} message='YFI/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'YFI/USDT'

ERROR 2022-03-30 23:12:40,660 catch_all_exceptions 14828 139710236186368 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'EOS/USDT', '1h', 40) kwargs={} message='EOS/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'EOS/USDT'

ERROR 2022-03-30 23:12:40,661 catch_all_exceptions 14828 139710236186368 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'DOT/USDT', '1h', 40) kwargs={} message='DOT/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'DOT/USDT'

ERROR 2022-03-30 23:12:40,663 catch_all_exceptions 14828 139710236186368 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'FIL/USDT', '1h', 40) kwargs={} message='FIL/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'FIL/USDT'

ERROR 2022-03-30 23:12:40,664 catch_all_exceptions 14828 139710236186368 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'ADA/USDT', '1h', 40) kwargs={} message='ADA/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'ADA/USDT'

ERROR 2022-03-30 23:12:40,665 catch_all_exceptions 14828 139710487594752 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'XRP/USDT', '1h', 40) kwargs={} message='XRP/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'XRP/USDT'

ERROR 2022-03-30 23:12:40,666 catch_all_exceptions 14828 139710487594752 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'LTC/USDT', '1h', 40) kwargs={} message='LTC/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'LTC/USDT'

ERROR 2022-03-30 23:12:40,667 catch_all_exceptions 14828 139710487594752 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'TRX/USDT', '1h', 40) kwargs={} message='TRX/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'TRX/USDT'

ERROR 2022-03-30 23:12:40,669 catch_all_exceptions 14828 139710487594752 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'GRT/USDT', '1h', 40) kwargs={} message='GRT/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'GRT/USDT'

ERROR 2022-03-30 23:12:40,670 catch_all_exceptions 14828 139710236186368 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'SUSHI/USDT', '1h', 40) kwargs={} message='SUSHI/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'SUSHI/USDT'

ERROR 2022-03-30 23:12:40,671 catch_all_exceptions 14828 139710236186368 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'XLM/USDT', '1h', 40) kwargs={} message='XLM/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'XLM/USDT'

ERROR 2022-03-30 23:12:40,672 catch_all_exceptions 14828 139710487594752 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, '1INCH/USDT', '1h', 40) kwargs={} message='1INCH/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: '1INCH/USDT'

ERROR 2022-03-30 23:12:40,674 catch_all_exceptions 14828 139710487594752 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'ZEC/USDT', '1h', 40) kwargs={} message='ZEC/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'ZEC/USDT'

ERROR 2022-03-30 23:12:40,675 catch_all_exceptions 14828 139710236186368 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'DASH/USDT', '1h', 40) kwargs={} message='DASH/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'DASH/USDT'

ERROR 2022-03-30 23:12:40,677 catch_all_exceptions 14828 139710236186368 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'AAVE/USDT', '1h', 40) kwargs={} message='AAVE/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'AAVE/USDT'

ERROR 2022-03-30 23:12:40,678 catch_all_exceptions 14828 139710227793664 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'DOGE/USDT', '1h', 40) kwargs={} message='DOGE/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'DOGE/USDT'

ERROR 2022-03-30 23:12:40,679 catch_all_exceptions 14828 139710487594752 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'KSM/USDT', '1h', 40) kwargs={} message='KSM/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'KSM/USDT'

ERROR 2022-03-30 23:12:40,680 catch_all_exceptions 14828 139710236186368 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'LUNA/USDT', '1h', 40) kwargs={} message='LUNA/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'LUNA/USDT'

ERROR 2022-03-30 23:12:40,681 catch_all_exceptions 14828 139710236186368 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'VET/USDT', '1h', 40) kwargs={} message='VET/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'VET/USDT'

ERROR 2022-03-30 23:12:40,683 catch_all_exceptions 14828 139710487594752 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'SXP/USDT', '1h', 40) kwargs={} message='SXP/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'SXP/USDT'

ERROR 2022-03-30 23:12:40,684 catch_all_exceptions 14828 139710236186368 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'BNB/USDT', '1h', 40) kwargs={} message='BNB/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'BNB/USDT'

ERROR 2022-03-30 23:12:40,686 catch_all_exceptions 14828 139710219400960 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'IOST/USDT', '1h', 40) kwargs={} message='IOST/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'IOST/USDT'

ERROR 2022-03-30 23:12:40,686 catch_all_exceptions 14828 139710227793664 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'SOL/USDT', '1h', 40) kwargs={} message='SOL/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'SOL/USDT'

ERROR 2022-03-30 23:12:40,689 catch_all_exceptions 14828 139710487594752 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'CRV/USDT', '1h', 40) kwargs={} message='CRV/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'CRV/USDT'

ERROR 2022-03-30 23:12:40,689 catch_all_exceptions 14828 139710236186368 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'ALGO/USDT', '1h', 40) kwargs={} message='ALGO/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'ALGO/USDT'

ERROR 2022-03-30 23:12:40,691 catch_all_exceptions 14828 139710487594752 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'AVAX/USDT', '1h', 40) kwargs={} message='AVAX/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'AVAX/USDT'

ERROR 2022-03-30 23:12:40,691 catch_all_exceptions 14828 139710487594752 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'MATIC/USDT', '1h', 40) kwargs={} message='MATIC/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'MATIC/USDT'

ERROR 2022-03-30 23:12:40,691 catch_all_exceptions 14828 139710487594752 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'ATOM/USDT', '1h', 40) kwargs={} message='ATOM/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'ATOM/USDT'

ERROR 2022-03-30 23:12:40,691 catch_all_exceptions 14828 139710236186368 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'FTM/USDT', '1h', 40) kwargs={} message='FTM/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'FTM/USDT'

ERROR 2022-03-30 23:12:40,692 catch_all_exceptions 14828 139710227793664 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'THETA/USDT', '1h', 40) kwargs={} message='THETA/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'THETA/USDT'

ERROR 2022-03-30 23:12:40,692 catch_all_exceptions 14828 139710219400960 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'CHZ/USDT', '1h', 40) kwargs={} message='CHZ/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'CHZ/USDT'

ERROR 2022-03-30 23:12:40,692 catch_all_exceptions 14828 139710487594752 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'ENJ/USDT', '1h', 40) kwargs={} message='ENJ/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'ENJ/USDT'

ERROR 2022-03-30 23:12:40,692 catch_all_exceptions 14828 139710211008256 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'DENT/USDT', '1h', 40) kwargs={} message='DENT/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'DENT/USDT'

ERROR 2022-03-30 23:12:40,693 catch_all_exceptions 14828 139710236186368 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'MANA/USDT', '1h', 40) kwargs={} message='MANA/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'MANA/USDT'

ERROR 2022-03-30 23:12:40,693 catch_all_exceptions 14828 139710202615552 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'OCEAN/USDT', '1h', 40) kwargs={} message='OCEAN/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'OCEAN/USDT'

ERROR 2022-03-30 23:12:40,693 catch_all_exceptions 14828 139710211008256 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'BAT/USDT', '1h', 40) kwargs={} message='BAT/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'BAT/USDT'

ERROR 2022-03-30 23:12:40,693 catch_all_exceptions 14828 139710236186368 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'XEM/USDT', '1h', 40) kwargs={} message='XEM/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'XEM/USDT'

ERROR 2022-03-30 23:12:40,694 catch_all_exceptions 14828 139710487594752 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'QTUM/USDT', '1h', 40) kwargs={} message='QTUM/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'QTUM/USDT'

ERROR 2022-03-30 23:12:40,694 catch_all_exceptions 14828 139710202615552 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'XTZ/USDT', '1h', 40) kwargs={} message='XTZ/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'XTZ/USDT'

ERROR 2022-03-30 23:12:40,694 catch_all_exceptions 14828 139710219400960 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'SNX/USDT', '1h', 40) kwargs={} message='SNX/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'SNX/USDT'

ERROR 2022-03-30 23:12:40,694 catch_all_exceptions 14828 139710211008256 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'NEO/USDT', '1h', 40) kwargs={} message='NEO/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'NEO/USDT'

ERROR 2022-03-30 23:12:40,694 catch_all_exceptions 14828 139710227793664 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'ONT/USDT', '1h', 40) kwargs={} message='ONT/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'ONT/USDT'

ERROR 2022-03-30 23:12:40,695 catch_all_exceptions 14828 139710236186368 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'XMR/USDT', '1h', 40) kwargs={} message='XMR/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'XMR/USDT'

ERROR 2022-03-30 23:12:40,695 catch_all_exceptions 14828 139710202615552 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'ETC/USDT', '1h', 40) kwargs={} message='ETC/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'ETC/USDT'

ERROR 2022-03-30 23:12:40,695 catch_all_exceptions 14828 139710487594752 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'COMP/USDT', '1h', 40) kwargs={} message='COMP/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'COMP/USDT'

ERROR 2022-03-30 23:12:40,695 catch_all_exceptions 14828 139709716100864 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'WAVES/USDT', '1h', 40) kwargs={} message='WAVES/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'WAVES/USDT'

ERROR 2022-03-30 23:12:40,696 catch_all_exceptions 14828 139710219400960 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'BAND/USDT', '1h', 40) kwargs={} message='BAND/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'BAND/USDT'

ERROR 2022-03-30 23:12:40,696 catch_all_exceptions 14828 139710211008256 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'MKR/USDT', '1h', 40) kwargs={} message='MKR/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'MKR/USDT'

ERROR 2022-03-30 23:12:40,696 catch_all_exceptions 14828 139709707708160 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'RVN/USDT', '1h', 40) kwargs={} message='RVN/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'RVN/USDT'

ERROR 2022-03-30 23:12:40,696 catch_all_exceptions 14828 139710227793664 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'DGB/USDT', '1h', 40) kwargs={} message='DGB/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'DGB/USDT'

ERROR 2022-03-30 23:12:40,697 catch_all_exceptions 14828 139709699315456 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'MIR/USDT', '1h', 40) kwargs={} message='MIR/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'MIR/USDT'

ERROR 2022-03-30 23:12:40,697 catch_all_exceptions 14828 139710236186368 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'SHIB/USDT', '1h', 40) kwargs={} message='SHIB/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'SHIB/USDT'

ERROR 2022-03-30 23:12:40,697 catch_all_exceptions 14828 139709690922752 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'ICP/USDT', '1h', 40) kwargs={} message='ICP/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'ICP/USDT'

ERROR 2022-03-30 23:12:40,697 catch_all_exceptions 14828 139710202615552 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'DYDX/USDT', '1h', 40) kwargs={} message='DYDX/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'DYDX/USDT'

ERROR 2022-03-30 23:12:40,698 catch_all_exceptions 14828 139709682530048 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'AXS/USDT', '1h', 40) kwargs={} message='AXS/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'AXS/USDT'

ERROR 2022-03-30 23:12:40,698 catch_all_exceptions 14828 139710487594752 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'HBAR/USDT', '1h', 40) kwargs={} message='HBAR/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'HBAR/USDT'

ERROR 2022-03-30 23:12:40,698 catch_all_exceptions 14828 139709716100864 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'EGLD/USDT', '1h', 40) kwargs={} message='EGLD/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'EGLD/USDT'

ERROR 2022-03-30 23:12:40,698 catch_all_exceptions 14828 139710219400960 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'ALICE/USDT', '1h', 40) kwargs={} message='ALICE/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'ALICE/USDT'

ERROR 2022-03-30 23:12:40,699 catch_all_exceptions 14828 139709674137344 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'YGG/USDT', '1h', 40) kwargs={} message='YGG/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'YGG/USDT'

ERROR 2022-03-30 23:12:40,699 catch_all_exceptions 14828 139710211008256 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'NEAR/USDT', '1h', 40) kwargs={} message='NEAR/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'NEAR/USDT'

ERROR 2022-03-30 23:12:40,699 catch_all_exceptions 14828 139709665744640 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'SAND/USDT', '1h', 40) kwargs={} message='SAND/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'SAND/USDT'

ERROR 2022-03-30 23:12:40,699 catch_all_exceptions 14828 139709707708160 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'C98/USDT', '1h', 40) kwargs={} message='C98/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'C98/USDT'

ERROR 2022-03-30 23:12:40,699 catch_all_exceptions 14828 139709179229952 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'ONE/USDT', '1h', 40) kwargs={} message='ONE/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'ONE/USDT'

ERROR 2022-03-30 23:12:40,700 catch_all_exceptions 14828 139710227793664 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'VRA/USDT', '1h', 40) kwargs={} message='VRA/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'VRA/USDT'

ERROR 2022-03-30 23:12:40,700 catch_all_exceptions 14828 139709699315456 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'GALA/USDT', '1h', 40) kwargs={} message='GALA/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'GALA/USDT'

ERROR 2022-03-30 23:12:40,700 catch_all_exceptions 14828 139709170837248 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'TLM/USDT', '1h', 40) kwargs={} message='TLM/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'TLM/USDT'

ERROR 2022-03-30 23:12:40,700 catch_all_exceptions 14828 139709162444544 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'CHR/USDT', '1h', 40) kwargs={} message='CHR/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'CHR/USDT'

ERROR 2022-03-30 23:12:40,700 catch_all_exceptions 14828 139710236186368 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'LRC/USDT', '1h', 40) kwargs={} message='LRC/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'LRC/USDT'

ERROR 2022-03-30 23:12:40,701 catch_all_exceptions 14828 139709690922752 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'FLOW/USDT', '1h', 40) kwargs={} message='FLOW/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'FLOW/USDT'

ERROR 2022-03-30 23:12:40,701 catch_all_exceptions 14828 139709154051840 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'RNDR/USDT', '1h', 40) kwargs={} message='RNDR/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'RNDR/USDT'

ERROR 2022-03-30 23:12:40,701 catch_all_exceptions 14828 139710202615552 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'IOTX/USDT', '1h', 40) kwargs={} message='IOTX/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'IOTX/USDT'

ERROR 2022-03-30 23:12:40,701 catch_all_exceptions 14828 139709145659136 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'CRO/USDT', '1h', 40) kwargs={} message='CRO/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'CRO/USDT'

ERROR 2022-03-30 23:12:40,701 catch_all_exceptions 14828 139709682530048 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'WAXP/USDT', '1h', 40) kwargs={} message='WAXP/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'WAXP/USDT'

ERROR 2022-03-30 23:12:40,702 catch_all_exceptions 14828 139709137266432 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'PEOPLE/USDT', '1h', 40) kwargs={} message='PEOPLE/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'PEOPLE/USDT'

ERROR 2022-03-30 23:12:40,702 catch_all_exceptions 14828 139710487594752 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'OMG/USDT', '1h', 40) kwargs={} message='OMG/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'OMG/USDT'

ERROR 2022-03-30 23:12:40,702 catch_all_exceptions 14828 139709716100864 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'LINA/USDT', '1h', 40) kwargs={} message='LINA/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'LINA/USDT'

ERROR 2022-03-30 23:12:40,702 catch_all_exceptions 14828 139709128873728 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'IMX/USDT', '1h', 40) kwargs={} message='IMX/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'IMX/USDT'

ERROR 2022-03-30 23:12:40,702 catch_all_exceptions 14828 139710219400960 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'NFT/USDT', '1h', 40) kwargs={} message='NFT/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'NFT/USDT'

ERROR 2022-03-30 23:12:40,703 catch_all_exceptions 14828 139708642359040 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'CELR/USDT', '1h', 40) kwargs={} message='CELR/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'CELR/USDT'

ERROR 2022-03-30 23:12:40,703 catch_all_exceptions 14828 139709674137344 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'ENS/USDT', '1h', 40) kwargs={} message='ENS/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'ENS/USDT'

ERROR 2022-03-30 23:12:40,703 catch_all_exceptions 14828 139710211008256 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'CELO/USDT', '1h', 40) kwargs={} message='CELO/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'CELO/USDT'

ERROR 2022-03-30 23:12:40,703 catch_all_exceptions 14828 139709665744640 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'CTSI/USDT', '1h', 40) kwargs={} message='CTSI/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'CTSI/USDT'

ERROR 2022-03-30 23:12:40,703 catch_all_exceptions 14828 139708633966336 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'SLP/USDT', '1h', 40) kwargs={} message='SLP/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'SLP/USDT'

ERROR 2022-03-30 23:12:40,705 catch_all_exceptions 14828 139709707708160 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'ARPA/USDT', '1h', 40) kwargs={} message='ARPA/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'ARPA/USDT'

ERROR 2022-03-30 23:12:40,705 catch_all_exceptions 14828 139708625573632 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'KNC/USDT', '1h', 40) kwargs={} message='KNC/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'KNC/USDT'

ERROR 2022-03-30 23:12:40,705 catch_all_exceptions 14828 139710227793664 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'API3/USDT', '1h', 40) kwargs={} message='API3/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'API3/USDT'

ERROR 2022-03-30 23:12:40,705 catch_all_exceptions 14828 139709179229952 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'SOS/USDT', '1h', 40) kwargs={} message='SOS/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'SOS/USDT'

ERROR 2022-03-30 23:12:40,706 catch_all_exceptions 14828 139709170837248 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'APE/USDT', '1h', 40) kwargs={} message='APE/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'APE/USDT'

ERROR 2022-03-30 23:12:40,706 catch_all_exceptions 14828 139708617180928 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'AGLD/USDT', '1h', 40) kwargs={} message='AGLD/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'AGLD/USDT'

ERROR 2022-03-30 23:12:40,706 catch_all_exceptions 14828 139709162444544 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'SRM/USDT', '1h', 40) kwargs={} message='SRM/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'SRM/USDT'

ERROR 2022-03-30 23:12:40,706 catch_all_exceptions 14828 139708608788224 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'JASMY/USDT', '1h', 40) kwargs={} message='JASMY/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'JASMY/USDT'

ERROR 2022-03-30 23:12:40,706 catch_all_exceptions 14828 139710236186368 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'ZIL/USDT', '1h', 40) kwargs={} message='ZIL/USDT' traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 73, in start_signal_generating_by_cci
    symbol_position_config = symbols_position_config[symbol]
KeyError: 'ZIL/USDT'

ERROR 2022-03-30 23:12:44,011 catch_all_exceptions 14828 139710252971776 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'LINK/USDT', '1h', 40) kwargs={} message=name 'cc' is not defined traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 78, in start_signal_generating_by_cci
    print(cc, prev_cci)
NameError: name 'cc' is not defined

ERROR 2022-03-30 23:12:44,558 catch_all_exceptions 14828 139710244579072 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'UNI/USDT', '1h', 40) kwargs={} message=name 'cc' is not defined traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 78, in start_signal_generating_by_cci
    print(cc, prev_cci)
NameError: name 'cc' is not defined

ERROR 2022-03-30 23:12:44,777 catch_all_exceptions 14828 139709699315456 func=<function start_signal_generating_by_cci at 0x7f10e1fcd670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f10e1fce9a0>, 'ROSE/USDT', '1h', 40) kwargs={} message=name 'cc' is not defined traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 78, in start_signal_generating_by_cci
    print(cc, prev_cci)
NameError: name 'cc' is not defined

ERROR 2022-03-30 23:14:12,593 retry_on_timeout 15033 140250999412480 kucoin does not have market symbol IOTX
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 17, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/spot_trader/exchange/exchange.py", line 60, in fetch_ohlcv
    return self._ccxt_exchange.fetch_ohlcv(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/ccxt/kucoin.py", line 751, in fetch_ohlcv
    market = self.market(symbol)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1989, in market
    raise BadSymbol('{} does not have market symbol {}'.format(self.id, symbol))
ccxt.base.errors.BadSymbol: kucoin does not have market symbol IOTX
ERROR 2022-03-30 23:14:12,599 catch_all_exceptions 15033 140250999412480 func=<function start_signal_generating_by_cci at 0x7f8ec9de5670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f8ec9de7a90>, 'IOTX', '1h', 40) kwargs={} message=too many indices for array: array is 0-dimensional, but 2 were indexed traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 77, in start_signal_generating_by_cci
    cci, prev_cci = TechnicalAnalyser.get_cci(symbol, timeframe, n)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/spot_trader/services/ta.py", line 17, in get_cci
    open_prices = pandas.Series(np_array[:, 1])
IndexError: too many indices for array: array is 0-dimensional, but 2 were indexed

ERROR 2022-03-30 23:14:13,720 retry_on_timeout 15033 140250479326976 kucoin does not have market symbol 1INCH
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 17, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/spot_trader/exchange/exchange.py", line 60, in fetch_ohlcv
    return self._ccxt_exchange.fetch_ohlcv(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/ccxt/kucoin.py", line 751, in fetch_ohlcv
    market = self.market(symbol)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1989, in market
    raise BadSymbol('{} does not have market symbol {}'.format(self.id, symbol))
ccxt.base.errors.BadSymbol: kucoin does not have market symbol 1INCH
ERROR 2022-03-30 23:14:13,720 catch_all_exceptions 15033 140250479326976 func=<function start_signal_generating_by_cci at 0x7f8ec9de5670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f8ec9de7a90>, '1INCH', '1h', 40) kwargs={} message=too many indices for array: array is 0-dimensional, but 2 were indexed traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 77, in start_signal_generating_by_cci
    cci, prev_cci = TechnicalAnalyser.get_cci(symbol, timeframe, n)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/spot_trader/services/ta.py", line 17, in get_cci
    open_prices = pandas.Series(np_array[:, 1])
IndexError: too many indices for array: array is 0-dimensional, but 2 were indexed

ERROR 2022-03-30 23:14:15,167 retry_on_timeout 15033 140250974234368 kucoin does not have market symbol MANA
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 17, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/spot_trader/exchange/exchange.py", line 60, in fetch_ohlcv
    return self._ccxt_exchange.fetch_ohlcv(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/ccxt/kucoin.py", line 751, in fetch_ohlcv
    market = self.market(symbol)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1989, in market
    raise BadSymbol('{} does not have market symbol {}'.format(self.id, symbol))
ccxt.base.errors.BadSymbol: kucoin does not have market symbol MANA
ERROR 2022-03-30 23:14:15,167 catch_all_exceptions 15033 140250974234368 func=<function start_signal_generating_by_cci at 0x7f8ec9de5670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f8ec9de7a90>, 'MANA', '1h', 40) kwargs={} message=too many indices for array: array is 0-dimensional, but 2 were indexed traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 77, in start_signal_generating_by_cci
    cci, prev_cci = TechnicalAnalyser.get_cci(symbol, timeframe, n)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/spot_trader/services/ta.py", line 17, in get_cci
    open_prices = pandas.Series(np_array[:, 1])
IndexError: too many indices for array: array is 0-dimensional, but 2 were indexed

ERROR 2022-03-30 23:14:15,619 retry_on_timeout 15033 140250965841664 kucoin does not have market symbol TRX
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 17, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/spot_trader/exchange/exchange.py", line 60, in fetch_ohlcv
    return self._ccxt_exchange.fetch_ohlcv(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/ccxt/kucoin.py", line 751, in fetch_ohlcv
    market = self.market(symbol)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1989, in market
    raise BadSymbol('{} does not have market symbol {}'.format(self.id, symbol))
ccxt.base.errors.BadSymbol: kucoin does not have market symbol TRX
ERROR 2022-03-30 23:14:15,619 catch_all_exceptions 15033 140250965841664 func=<function start_signal_generating_by_cci at 0x7f8ec9de5670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f8ec9de7a90>, 'TRX', '1h', 40) kwargs={} message=too many indices for array: array is 0-dimensional, but 2 were indexed traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 77, in start_signal_generating_by_cci
    cci, prev_cci = TechnicalAnalyser.get_cci(symbol, timeframe, n)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/spot_trader/services/ta.py", line 17, in get_cci
    open_prices = pandas.Series(np_array[:, 1])
IndexError: too many indices for array: array is 0-dimensional, but 2 were indexed

ERROR 2022-03-30 23:14:16,655 retry_on_timeout 15033 140250991019776 kucoin does not have market symbol FTM
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 17, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/spot_trader/exchange/exchange.py", line 60, in fetch_ohlcv
    return self._ccxt_exchange.fetch_ohlcv(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/ccxt/kucoin.py", line 751, in fetch_ohlcv
    market = self.market(symbol)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1989, in market
    raise BadSymbol('{} does not have market symbol {}'.format(self.id, symbol))
ccxt.base.errors.BadSymbol: kucoin does not have market symbol FTM
ERROR 2022-03-30 23:14:16,656 catch_all_exceptions 15033 140250991019776 func=<function start_signal_generating_by_cci at 0x7f8ec9de5670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f8ec9de7a90>, 'FTM', '1h', 40) kwargs={} message=too many indices for array: array is 0-dimensional, but 2 were indexed traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 77, in start_signal_generating_by_cci
    cci, prev_cci = TechnicalAnalyser.get_cci(symbol, timeframe, n)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/spot_trader/services/ta.py", line 17, in get_cci
    open_prices = pandas.Series(np_array[:, 1])
IndexError: too many indices for array: array is 0-dimensional, but 2 were indexed

ERROR 2022-03-30 23:14:16,994 retry_on_timeout 15033 140250982627072 kucoin does not have market symbol MATIC
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 17, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/spot_trader/exchange/exchange.py", line 60, in fetch_ohlcv
    return self._ccxt_exchange.fetch_ohlcv(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/ccxt/kucoin.py", line 751, in fetch_ohlcv
    market = self.market(symbol)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1989, in market
    raise BadSymbol('{} does not have market symbol {}'.format(self.id, symbol))
ccxt.base.errors.BadSymbol: kucoin does not have market symbol MATIC
ERROR 2022-03-30 23:14:16,995 catch_all_exceptions 15033 140250982627072 func=<function start_signal_generating_by_cci at 0x7f8ec9de5670> args=(<futures_trader.clients.public_client.PublicClient object at 0x7f8ec9de7a90>, 'MATIC', '1h', 40) kwargs={} message=too many indices for array: array is 0-dimensional, but 2 were indexed traceback=Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/catch_all_exceptions.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/services/technical_trader/auto_trader.py", line 77, in start_signal_generating_by_cci
    cci, prev_cci = TechnicalAnalyser.get_cci(symbol, timeframe, n)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/spot_trader/services/ta.py", line 17, in get_cci
    open_prices = pandas.Series(np_array[:, 1])
IndexError: too many indices for array: array is 0-dimensional, but 2 were indexed

ERROR 2022-03-30 23:14:57,318 retry_on_timeout 15114 140278245611264 kucoin does not have market symbol MANA
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 17, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/spot_trader/exchange/exchange.py", line 60, in fetch_ohlcv
    return self._ccxt_exchange.fetch_ohlcv(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/ccxt/kucoin.py", line 751, in fetch_ohlcv
    market = self.market(symbol)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1989, in market
    raise BadSymbol('{} does not have market symbol {}'.format(self.id, symbol))
ccxt.base.errors.BadSymbol: kucoin does not have market symbol MANA
ERROR 2022-03-30 23:14:57,546 retry_on_timeout 15114 140278262396672 kucoin does not have market symbol FTM
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 17, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/spot_trader/exchange/exchange.py", line 60, in fetch_ohlcv
    return self._ccxt_exchange.fetch_ohlcv(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/ccxt/kucoin.py", line 751, in fetch_ohlcv
    market = self.market(symbol)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1989, in market
    raise BadSymbol('{} does not have market symbol {}'.format(self.id, symbol))
ccxt.base.errors.BadSymbol: kucoin does not have market symbol FTM
ERROR 2022-03-30 23:14:58,106 retry_on_timeout 15114 140278613694208 kucoin does not have market symbol IOTX
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 17, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/spot_trader/exchange/exchange.py", line 60, in fetch_ohlcv
    return self._ccxt_exchange.fetch_ohlcv(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/ccxt/kucoin.py", line 751, in fetch_ohlcv
    market = self.market(symbol)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1989, in market
    raise BadSymbol('{} does not have market symbol {}'.format(self.id, symbol))
ccxt.base.errors.BadSymbol: kucoin does not have market symbol IOTX
ERROR 2022-03-30 23:14:58,473 retry_on_timeout 15114 140278228825856 kucoin does not have market symbol 1INCH
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 17, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/spot_trader/exchange/exchange.py", line 60, in fetch_ohlcv
    return self._ccxt_exchange.fetch_ohlcv(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/ccxt/kucoin.py", line 751, in fetch_ohlcv
    market = self.market(symbol)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1989, in market
    raise BadSymbol('{} does not have market symbol {}'.format(self.id, symbol))
ccxt.base.errors.BadSymbol: kucoin does not have market symbol 1INCH
ERROR 2022-03-30 23:14:58,936 retry_on_timeout 15114 140278254003968 kucoin does not have market symbol MATIC
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 17, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/spot_trader/exchange/exchange.py", line 60, in fetch_ohlcv
    return self._ccxt_exchange.fetch_ohlcv(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/ccxt/kucoin.py", line 751, in fetch_ohlcv
    market = self.market(symbol)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1989, in market
    raise BadSymbol('{} does not have market symbol {}'.format(self.id, symbol))
ccxt.base.errors.BadSymbol: kucoin does not have market symbol MATIC
ERROR 2022-03-30 23:14:58,946 retry_on_timeout 15114 140278237218560 kucoin does not have market symbol TRX
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 17, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/spot_trader/exchange/exchange.py", line 60, in fetch_ohlcv
    return self._ccxt_exchange.fetch_ohlcv(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/ccxt/kucoin.py", line 751, in fetch_ohlcv
    market = self.market(symbol)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1989, in market
    raise BadSymbol('{} does not have market symbol {}'.format(self.id, symbol))
ccxt.base.errors.BadSymbol: kucoin does not have market symbol TRX
ERROR 2022-03-30 23:16:20,327 retry_on_timeout 15253 140088117806848 kucoin does not have market symbol MANA
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 17, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/spot_trader/exchange/exchange.py", line 60, in fetch_ohlcv
    return self._ccxt_exchange.fetch_ohlcv(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/ccxt/kucoin.py", line 751, in fetch_ohlcv
    market = self.market(symbol)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1989, in market
    raise BadSymbol('{} does not have market symbol {}'.format(self.id, symbol))
ccxt.base.errors.BadSymbol: kucoin does not have market symbol MANA
ERROR 2022-03-30 23:16:20,523 retry_on_timeout 15253 140088126199552 kucoin does not have market symbol FTM
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 17, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/spot_trader/exchange/exchange.py", line 60, in fetch_ohlcv
    return self._ccxt_exchange.fetch_ohlcv(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/ccxt/kucoin.py", line 751, in fetch_ohlcv
    market = self.market(symbol)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1989, in market
    raise BadSymbol('{} does not have market symbol {}'.format(self.id, symbol))
ccxt.base.errors.BadSymbol: kucoin does not have market symbol FTM
ERROR 2022-03-30 23:16:20,792 retry_on_timeout 15253 140088134592256 kucoin does not have market symbol IOTX
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 17, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/spot_trader/exchange/exchange.py", line 60, in fetch_ohlcv
    return self._ccxt_exchange.fetch_ohlcv(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/ccxt/kucoin.py", line 751, in fetch_ohlcv
    market = self.market(symbol)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1989, in market
    raise BadSymbol('{} does not have market symbol {}'.format(self.id, symbol))
ccxt.base.errors.BadSymbol: kucoin does not have market symbol IOTX
ERROR 2022-03-30 23:16:21,691 retry_on_timeout 15253 140088101021440 kucoin does not have market symbol 1INCH
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 17, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/spot_trader/exchange/exchange.py", line 60, in fetch_ohlcv
    return self._ccxt_exchange.fetch_ohlcv(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/ccxt/kucoin.py", line 751, in fetch_ohlcv
    market = self.market(symbol)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1989, in market
    raise BadSymbol('{} does not have market symbol {}'.format(self.id, symbol))
ccxt.base.errors.BadSymbol: kucoin does not have market symbol 1INCH
ERROR 2022-03-30 23:16:23,547 retry_on_timeout 15253 140088109414144 kucoin does not have market symbol TRX
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 17, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/spot_trader/exchange/exchange.py", line 60, in fetch_ohlcv
    return self._ccxt_exchange.fetch_ohlcv(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/ccxt/kucoin.py", line 751, in fetch_ohlcv
    market = self.market(symbol)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1989, in market
    raise BadSymbol('{} does not have market symbol {}'.format(self.id, symbol))
ccxt.base.errors.BadSymbol: kucoin does not have market symbol TRX
ERROR 2022-03-30 23:16:23,679 retry_on_timeout 15253 140088523872000 kucoin does not have market symbol MATIC
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 17, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/spot_trader/exchange/exchange.py", line 60, in fetch_ohlcv
    return self._ccxt_exchange.fetch_ohlcv(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/ccxt/kucoin.py", line 751, in fetch_ohlcv
    market = self.market(symbol)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1989, in market
    raise BadSymbol('{} does not have market symbol {}'.format(self.id, symbol))
ccxt.base.errors.BadSymbol: kucoin does not have market symbol MATIC
ERROR 2022-03-30 23:30:39,290 bot_handler 16307 140304587433728 Creating bot failed because position with symbol 1INCH/USDT is duplicate!
