ERROR 2022-02-21 13:08:21,314 retry_on_timeout 84967 139963272259328 200-{"code":"300009","msg":"Current position size: 0, unable to close the position."}
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 17, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/exchange/exchange.py", line 61, in close_position
    exchange_order = self._sdk_exchange.trade_client.create_market_order(symbol=symbol,
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/trade/trade.py", line 370, in create_market_order
    return self._request('POST', '/api/v1/orders', params=params)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 91, in _request
    return self.check_response_data(response_data)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 108, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 200-{"code":"300009","msg":"Current position size: 0, unable to close the position."}
ERROR 2022-02-21 13:25:14,461 retry_on_timeout 85662 140632882042688 500-{"code":"100000","msg":"Service not available temporarily, please try it later."}
Traceback (most recent call last):
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/global_utils/retry_on_timeout.py", line 17, in caught_func
    _result, _error = func(*args, **kwargs), False
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/futures_trader/exchange/exchange.py", line 30, in get_orders
    return self._sdk_exchange.trade_client.get_open_order_details(symbol)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/trade/trade.py", line 299, in get_open_order_details
    return self._request('GET', '/api/v1/openOrderStatistics', params=params)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 91, in _request
    return self.check_response_data(response_data)
  File "/home/mohammad/others/codes/intellichange/DJANGO-algorithmic_trading/venv/lib/python3.8/site-packages/kucoin_futures/base_request/base_request.py", line 110, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 500-{"code":"100000","msg":"Service not available temporarily, please try it later."}
